---
- name: Get webhook notifications {{ webhook_config.key }}
  ansible.builtin.command:
    pvesh get /cluster/notifications/endpoints/webhook --output-format json
  changed_when: false
  register: existing_webhook

- name: Add webhook endpoint {{ webhook_config.key }}
  vars:
    create_params: >-
      {% for key, value in webhook_config.value.items() %}
        {% if key not in ['header', 'secret'] %}
        --{{ key }} '{{ value }}'
        {% endif %}
        {% if key in ['header', 'secret'] %}
          {% for item in value %}
          --{{ key }} '{{ item }}'
          {% endfor %}
        {% endif %}
      {% endfor %}
  ansible.builtin.command:
    pvesh create /cluster/notifications/endpoints/webhook --name {{ webhook_config.key }} {{ create_params }}
  when: "webhook_config.key not in existing_webhook.stdout | from_json | json_query('[].name')"
  changed_when: true