---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - cilium/app.yaml
  - cert-manager/app.yaml
  - democratic-csi/app-snapshotter.yaml
  - metrics-server/app.yaml
  - node-feature-discovery/app.yaml
  - nvidia-device-plugin/app.yaml
  - nvidia-device-plugin/configs.yaml
  - velero/app.yaml
