---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - alertmanager/app.yaml
  - cilium/app.yaml
  - cert-manager/app.yaml
  - snapshot-controller/app.yaml
  - gateway-api/app.yaml
  - kromgo/app.yaml
  - metrics-server/app.yaml
  - node-feature-discovery/app.yaml
  - nvidia-device-plugin/app.yaml
  - prometheus-operator/app.yaml
  - spegel/app.yaml
  - tailscale-operator/app.yaml
  - tuppr/app.yaml
  - velero/app.yaml
