generators:
  - secret-generator.yaml

resources:
  - cilium/app.yaml
  - cert-manager/app.yaml
  - metrics-server/app.yaml
  - node-feature-discovery/app.yaml
  - nvidia-device-plugin/app.yaml
  - nvidia-device-plugin/configs.yaml
