apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./cert-manager/configs.sops.yaml
  - ./democratic-csi/app-nfs.sops.yaml
  - ./democratic-csi/app-iscsi.sops.yaml