---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: arr-scripts
    files:
      - scripts/xseed.sh
      - scripts/cleanup_unused_quality_profiles.sh

generatorOptions:
  disableNameSuffixHash: true
