---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app external-dns-cloudflare
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: network

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://kubernetes-sigs.github.io/external-dns depName=external-dns
      value: external-dns@1.20.0
    - name: Image
      # renovate: datasource=docker depName=registry.k8s.io/external-dns/external-dns
      value: registry.k8s.io/external-dns/external-dns:v0.22.0@sha256:5fdcaf7deb5c158f93a1fc6fe169cdff4cfb9ae0172bee1a90ab0ef74fb9c9cf

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/infra/external-dns-cloudflare/
    targetRevision: main
