apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
    namespace: network
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:hSDXb9U4a7dKxIRm116M7T3yq9v60sIr9NrFbNrIBnk=,iv:9M4Maqqa9g9CJLgnxbAyZIaQv+OmXsH4BFiDte+CEb4=,tag:Sw+RCc4TmeI/Wox4Srrejw==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QStYZjlDQUg1d0VPNjYx
            SFJGUUY0YXY1allaSGtCdDg1NGdXcDN0OFdVClhzVGVkdGJTUXpSbm9ZU0MwK253
            RGt2SjNmV29jYzhvenRVU1pkRVcxMWMKLS0tIHRaV0NJeDlOMUk4NnNzUmh5YVFo
            S0tIa0I3cWhNTHVlMlo4bFVTdFZXRDAK6mlaDrzL9I9g58t+Su2WMHRYr6byW3dO
            fracBYWWSr/TwfbFFXSJR8I4NCOZf1oZQzNKFO4qEESVlStBWwT3mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:16:04Z"
    mac: ENC[AES256_GCM,data:oNa7qzZvlPEHc2QsHKn+6X70Dg40ZrBq65v3NYS4UNI2ih0cKBTtTb8inNVMza63u075oJ/KdOABnM74+dmNKBUvgZZ8mMoBMQHCXVP8O/g2Yr/mznQxnG/kG8U+RsWsiONMe8Eelw2ezrLoAvs1GBv/tr96P2zFToYHtoG/2hw=,iv:wC/CaKAvjyQQpZJWZmDVM9LLHnbuaiSo4+2Fi2/OL9M=,tag:7BIQTJ9L+hPDF/Zcf7wLFQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
