apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
    namespace: network
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:shbn4PAKJROf5DpyR21s5Yhx256KcVr7r1E50aMbb0hbA+DzqiDR9w==,iv:B77SrygpBYeuz8GbVdoCUpFT82o35MKjZOhngbO1Zew=,tag:jHPkEgZPOHDDbp+o6uBM/A==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QStYZjlDQUg1d0VPNjYx
            SFJGUUY0YXY1allaSGtCdDg1NGdXcDN0OFdVClhzVGVkdGJTUXpSbm9ZU0MwK253
            RGt2SjNmV29jYzhvenRVU1pkRVcxMWMKLS0tIHRaV0NJeDlOMUk4NnNzUmh5YVFo
            S0tIa0I3cWhNTHVlMlo4bFVTdFZXRDAK6mlaDrzL9I9g58t+Su2WMHRYr6byW3dO
            fracBYWWSr/TwfbFFXSJR8I4NCOZf1oZQzNKFO4qEESVlStBWwT3mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:29:09Z"
    mac: ENC[AES256_GCM,data:CNgbHX0ldUU0B8kw/15/BqqjufJSWEXLL1RbPZOkldzvv7HWlelfUJ2CR3TGu1R5nFZLR9THPdXUFyg7icqU+3qcTxpbHalfJSTbHrd9unlcl2QsoPsjjxFzJ0yyTFY7v7ckvl7O4/F4D+mI4dWtrJp+BrpV+r/204MzWb1OUR4=,iv:fQbnCyvd0NtUuaNBlNgWGNh2K1tpMPgsYNSJPU4Wh7A=,tag:CbTXVHfhHZXbg9T81mHL3Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
