---
fullnameOverride: external-dns-cloudflare

image:
  repository: registry.k8s.io/external-dns/external-dns
  tag: v0.20.0@sha256:ddc7f4212ed09a21024deb1f470a05240837712e74e4b9f6d1f2632ff10672e7

provider:
  name: cloudflare

sources:
  - gateway-httproute

domainFilters:
  - peterson.com.ar

excludeDomains:
  - lan.peterson.com.ar

policy: sync
registry: txt
txtOwnerId: homelab-cloudflare
txtPrefix: _edns.

extraArgs:
  - --default-targets=ashton.peterson.com.ar
  - --force-default-targets
  - --gateway-label-filter=external-dns/zone=public

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare-secret
        key: api-token

serviceMonitor:
  enabled: true
