---
fullnameOverride: external-dns-cloudflare

image:
  repository: registry.k8s.io/external-dns/external-dns
  tag: v0.22.0@sha256:5fdcaf7deb5c158f93a1fc6fe169cdff4cfb9ae0172bee1a90ab0ef74fb9c9cf

provider:
  name: cloudflare

sources:
  - gateway-httproute

domainFilters:
  - peterson.com.ar

excludeDomains:
  - lan.peterson.com.ar

policy: sync
registry: txt
txtOwnerId: homelab-cloudflare
txtPrefix: _edns.

extraArgs:
  - --default-targets=ashton.peterson.com.ar
  - --force-default-targets
  - --gateway-label-filter=external-dns/zone=public

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare-secret
        key: api-token

serviceMonitor:
  enabled: true
