---
"area/ci":
  - changed-files:
      - any-glob-to-any-file: ".github/**"

"area/kubernetes":
  - changed-files:
      - any-glob-to-any-file: "kubernetes/**"

"area/ansible":
  - changed-files:
      - any-glob-to-any-file: "ansible/**"

"area/talos":
  - changed-files:
      - any-glob-to-any-file: "talos/**"

"area/docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"

"critical-infra":
  - changed-files:
      - any-glob-to-any-file:
          - "kubernetes/infra/cilium/**"
          - "kubernetes/infra/gateway-api/**"
          - "hack/talos/**"
          - "talos/**"
