---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cross-seed-configs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/cross-seed/
    targetRevision: main
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-3.7.3/charts/library/common/values.schema.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app cross-seed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.1
    helm:
      valuesObject:
        strategy: RollingUpdate
        
        controllers:
          cross-seed:
            replicas: 1
            pod:
              securityContext:
                runAsUser: 65534
                runAsGroup: 100
                fsGroup: 65534
                fsGroupChangePolicy: "OnRootMismatch"

            containers:
              app:
                image:
                  repository: ghcr.io/cross-seed/cross-seed
                  tag: 6.12.7@sha256:84f50b090f732254d3846ad77c8bf9f451fd169465c88b3da4fec715da29a5ff
                args:
                  - daemon
                  - -v
                probes:
                  liveness:
                    enabled: true
                  readiness:
                    enabled: true
                  startup:
                    enabled: true
                    spec:
                      failureThreshold: 30
                      periodSeconds: 5
                resources:
                  requests:
                    cpu: 10m
                    memory: 128Mi
                  limits:
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL

        service:
          app:
            controller: *app
            ports:
              http:
                port: &port 2468

        persistence:
          config:
            storageClass: zfs-generic-iscsi-csi-xfs
            accessMode: ReadWriteOnce
            size: 500Mi
            advancedMounts:
              cross-seed:
                app:
                  - path: /config
          config-file:
            type: secret
            name: cross-seed-secret
            globalMounts:
              - path: /config/config.js
                subPath: config.js
                readOnly: true
          media:
            type: nfs
            server: nas.lan.peterson.com.ar
            path: /nibbler/media/library/
            globalMounts:
              - path: /data/streaming
                subPath: streaming
              - path: /data/downloads
                subPath: downloads