kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: cross-seed-secret
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    xseed_api_key: ENC[AES256_GCM,data:aF9GktL37xiv+vmo/uWQKai3cJNccWcW,iv:bAycyvHyylZDiY68HqtLlBGIcr/YbzCcGrmMXwL3JD8=,tag:Aky1N5vj2gBS/cZPMzHOBA==,type:str]
    config.js: ENC[AES256_GCM,data:IkK72+nqs94CbzI1rFlnF/tWS5I5paQn1ftKhqOxA5T1VocbTGdtpRKMbZJ2FwXrpLTZGwV8DgG0eUEpqtPGSa7aCPvzzT+K6c1upJdOZCOXTw3braO8DIYaK1GmWMF1YiuLUORXyheQPPxRWhNz7cJ1nYGwTkpEGH0HCx8vHNoDFer1z0CFv2ltEYGbqNjBAjxl7HWrSwv5XGSViWVqXEp0DHuidJe/gMbQjpKh9Z5cXKwYuPCK+L8+jsJFxgnxLQk/DLqgtzQx3pXoBbzoBdvjq5EN3OD8YDu8uV9uHBcRY57dklSC543sdc11wd3K3Xd/4m+p41qKyasobpaW9OyVWPS61tmU2AnpyBDJki1NPnQ0uYKIAn2g3QNahOkwNL9QhnPz66wztttRu1Bjc0dN4OcPnmUXsp5SzRdvGJb7LKVFMsD110hk+A1bZCSNJBHv7dQOGspCSGzWX2jdKxkthV+t8b8ZDwMrJ8wm+D1vlDNcnZqUrEEICIolblYGh35cTOcyGgo9dIMAut5pa/h35hEIpguyRk0TrZAhV2d+TIJ8XKR7ikGYz1POhbMuJqc9Pbclj2S/fj7HLaJRY8Q3gd5XwTHoWysYA4JEPYFOL0g2xwIR8wPrv0ceg3OBfdlL9XARJyf4JKkNGpPfCZTkl7ZER+PCh8pX+4QerYmAxr9qqT2bw56eQA+5N29c74wOfpE4B0KdQTWGI15GY2aKYabUk0dZAOMBQyoyv6laXbxfIqoBveh7P3+Esucfp5aL5r35LjEH7eI4gqPjLaLkxbkL3mibllM6j1we0hsPGyyzjlWAZNIFTav2yt0B7IZJysVGcB0ICiGe//xEFSYSLO6Q1JBxHtL4+WOfTTWAGyCblcsG9t84rOAO2UsHy2KhaDRW/PbsHrf8edxs+CiRehNuafX1bKlD601JJpbA7b6Cm2cKz6L2L4GzxhpA3Xmo/RIMvIvrj+xE6uvAZA3Am/V/tC95XS2JdA8b9JEje/RdxsQic4+OOl1vf/Cem59PMeqk+0HC8K15wFxQ8ckM5AyWQkTOGqUjsvs+MX7mF4z3/X7o3+6lCsmc2JbX0iTUtEbcIfKTKdmmOz7oOHUNUXi0Ly+WKje8+de8Ees6FZPLAMRsd/0qUxfmuPldgfqFYUyDc3G2S4nm7+gWlIhXuWHo67a8Y/NJueN1iZIgVS+dmzQ/4m7LLbwtTFSp8ZL9AI1XZTCweA6sDKI3GJzrSV1m46o0L3LRdE1VMji3+0V7BqyrhQ==,iv:4swDzxW3V07c3702DFa7wXL6g7GmiIahWIs6Q3RIRYE=,tag:mP+LFKRGCK3p4ybJ9wxLaQ==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUGJQV0syczN4QTFXRmIx
            ZDBzZEl5enV5ejBGeXZES1lLNXpJODZtWkJJCkpkNGV5UEdsU3BaTXM5YmJhUzZJ
            UVdGYUxtdytMV1FnTmlHTG1wVFhCSFEKLS0tIFJaaVZzRlE1Z1l0TTdmaHl4dHVQ
            VUM2YTdNRjRya0JqWCtqcEJORVhXbkUKnx+jJAJq9ZDfGXQlAAxd80DRQpC2N4LT
            TwWJSJOP4I4tI9G6K568V6GGf+s98aYg6PYVvG9QHFl08W+Y6V7OEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:12Z"
    mac: ENC[AES256_GCM,data:CJUC4edcRtWjoySbUxHeMZ7YMHpFqhJrDlRSKLVLkHAVWiQ0bEdlQG76reYX0+Ds+XqoT7FtwOQJE+ezuW7zZCd79dQ2zjrGjr52E5JLuj/7VSMiv7NScN1kMOG/KKBspprCWseZ5hF7zKYntNO0s2qS+Wqmdo9Vs+X60WZYi6E=,iv:h0rcCFNnS/4tZdPNeZCOLSorOfvelfI5n421Fv5tXuU=,tag:tIrOFOLlPcOp+xVOOo71Fg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
