kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: cross-seed-secret
    namespace: media
stringData:
    xseed_api_key: ENC[AES256_GCM,data:JRgZ/R3NZQXA9//Pq/ScSrIpS5q3DFAj,iv:2e9mt/OlAlEDsEwOhGCRwUuTuBRUjujUi7+nnMo62M8=,tag:ZYp6pqTgC/wz8r0gRQQLAA==,type:str]
    config.js: ENC[AES256_GCM,data:RKYginSo0IdRgoPViTPJOwknOXtisWRbj/UUZW+t8ancGysj13pDXt+kG6fo7NYclsUVz/KqpkY2OVOBRZRsQhrTxyPGuTVMTkpYhtEFD8DVjb3z4cnWy5APu6WMCbhR1eg+VslyJFyR6DZmk/q7drpkVUM3Fxr2VOt3PEX8NPibul8OlVD8hXNcIFw5skcl9GF7WCf6wPkQs6roraO19fPcT1B7lrjQmxODmSksBuQQ6w0rIoUs+9z5XOcP41pBIMxzBQzUggVbUBDWrWH2LvXUdm6Z6Rm5HEjpJi7MOlnMckwaEI6M8qOMxaFDyctyVEA8FhaveuMOpqo8KxqEAZJjN9FhSEYTb34Lw4BWctEidh4Ok6Dd57axgHvBPBfUB1kTEXwiWROPngSjH5SXBzZ4UZzjl4WRdkRLKQPM28PF+nAVE0zAGiWQ+sy+2i6r9rdyLJfgq37TgJAw9KrVLFGg8GuV31KAEiBXz65Ok+JL2J+Jn4KaFKoc7+C5xreduVVFjYL5xqbzLw5lpsyoyat7ppXxKk01As8cFTzxwfqETJWtiBABzTgwAsuCQ4ScEKlYlNJCIxAHcathEv8w2+tM4EeK/R2thqRCT4uoCw3WXELNeJVsaSOvb0/lwjDWz10HtHi8cmvHbVgTbgV2/h6MOTSyGg56z8+ay5xxtQYNryY8Tdydfc328ZQncXxz9/F3X6N6eyc31i+MO2C819AjQHLM+ITsmX23BLTnHB2HcBrR9KnQr3TMD5WQtepdOKJVLA8n8QSLzpm3URbL5MhHZOiSasffBYqhvemwSj7JLbLqJRfgkE9QQmDGPyio6LrzeaL5r7hb8J7Vg/gMiDXO5y3UdD0NQTOOJ88i3O7Xm2yt/HZXbLCvYZyvH3I7mLZ4+O1XkdNFrUT0ZHCNgwAIUVgyVcYbj+Q6+tTk+9njXhMADcmdD8VauJmVRw2AQ4YSDKtE6wJmP9eFqjCACtlvJdXW8Y0NX46kLGo8xXiyFring1MVFSqpumV3N9B5zHDbviNqRLqe9vkSH8DxHIR6xv76Qv69aZ94rYNyVBKWzcKDAYykFx3mQMPui/yDqb1y3fmrPSBWr8kVsRdS+hi5HTOxRigd2SSK/xPdMxHqQtf8/jE4rM9vXzEvNmaWFcJDYJFLl5dXbesHI1ztK18lNKjGhU7yP2UukJNuZuv8cPDryWg0hm5og7wuw15fJ71fK5DqKrPQiRvyQa5exolfKBplhJLXM1quy6XhfDrMpSaCCgupSA==,iv:ZceekzBWDeyMkKUPk0bnR5RaLlJ3ylU0eWbjIdPIVl4=,tag:kSdCQYiCfdKI889jbTAAxg==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RjV1SjZ4VkxGbTBreGZ5
            QjlrdW5ub0hieEVucVRudTZ2Y0FiYm5MQ0VnClRrQmNiVjJ4MFlpUnNubjI3Vnp4
            YUd3UEhtRXhndEg5SlhkWW5xT1lldUUKLS0tIDMySGRpcU4ycnJBbjFuais1dWs4
            KzE1ellIUytUcmtEZGN1eDZrZ3oybzgKTxQhAuu1JLHcSlk8RkqaJFi2oxneJG5m
            moOkiZD1qPFC0jyQNiZNGBhgMDyYcUZpDqgB9i3Me434SiLuaP6Hsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:01:05Z"
    mac: ENC[AES256_GCM,data:smCKS1kzxb5V8UROjwm3Cbt6Q4206CBLGiYtDv3O2a+9PHwSONRslIFQZTnTzZWMEbtn/VBQh+7GmGpZiJwhnS8lWYQwGa4cgIpvqI6fLBkryw9wKYKIS6vjYDkuc2KkWm+HygNTXAqxCQrmg45BWvY5EnzhibE68XaRTmlCYKY=,iv:xgRoUhic6Ufkug7TjqLXzElJNY0KKU7xqixXBSfkM6Q=,tag:L6cPHV/iwDMgPH+3csT8rg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
