kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: cross-seed-secret
    namespace: media
stringData:
    xseed_api_key: ENC[AES256_GCM,data:IOVAQbrQ00eDUNNDKFkjl697GT2N2Zh+,iv:DxTUySHSO4/EuKaZJgZB3V44SRWDJZ754VJB/ErbLt0=,tag:j+VoFGzUbJ8MVnSs3od9YA==,type:str]
    config.js: ENC[AES256_GCM,data:/ATIbHo9OWKid2BHU0YRz5jEYCXmGEcry0lQGE/1neh7cW9z4wac8xwKxoONJJRIw1P7VySzmO8moTs9RQ+XMQ1psJRz6VdYL4m793hTcBrTizuUylCBG2bIXQ/WSErdHT/u3uwnQXfYv0XCAZrEjYNf7EJ0b88D7YYE+QsDTFDI+6Ktc59WQvZ5DHI8uVFAjZY8aiKoYoFFk0lyOWOFov188CjDTy+xFaMV14iJ63auXQe0A5kjBZO5frU6vEICJYPJMsUi9IKe8VdpqUO3qe+QaXB5QaimfAQQLIL/YHpEaNuUXZdbllkNDAMwYukpplSrSX81Z1/akKwSFpjMbeoQoirpGSIPugXspjWn9/d/ggVXGnQIiYDuxKb/TyWRLVWd8crZ2kAZzABP46nlR5bOmQWfuywrPO5A+UuKd/I6UEIlRzF5H4bIk5uvX5d6TnAwAWdoYzCssgWC8P5ij7ug65wDqwIlx0pI3o+SwU/hlGFWejoynKTv63KHliFvY4SI84oP74xVf5hOqYbSENYJS60HycCzE1MAvhi/TDhk42DQCHSYYYpC45BxJSy/5Ifsq0BZJmrDfu9nSd5L7IuEbyaoIB+cvmTU4xPj7brSfRwJUhEEMvuKttsziFfUz3au3eXoMp+RPUfC/TUKYDF9YV3DSJzsSgp7JWD8Zs6qBXUreZfkzcFhX5w0PGv1ng3EDxgYa1yInpHGBMNkA4oWQrgaqKBv2DBmj3uW8sJzN0csIeA+z9VGjUYE6q8gmBx1yX9wHl5JqEbSTxkPseT/5lDoizLwUdTd7PB4sTp+VxZ6XO+mugFSp5yn0zTi/vFeO/VcX3WQ9g+XYIggKoaf1CqwpYHy5phskO2S7dXTjMwkiBOdWQWxZ9fUnsZRWrcKQUK+RWnbPEG+/B8Q+Bpt2cFavpZhNtzc7FiOpKeuHFphoRh9QPvQmhB1pOTrMWiw4yYtvlXvJ1vQclAHKBAf47oL654CSYr0ls63itpJIYdQobl77vggcv6fSCrZDwQWfJv2nLVXFHg9E2DM51G6+0zB5HdKVS3UC+3QHR96TgjPg343K5fzxRKOTkf9/9IaaQNeBdK7xxrI5v3547P4TvHF81HeMUKnqd1vGoMW7ZatfH5/Y3OO/kjiFgzN0manXd7hS3tR4sNnZ6L5ioQsMncffzTZNVI8U/im5XyoUBbCohdrGdeZzLyQNOS3yTnAzleFkWNG4v4w5sFoRKB1U++u/M6awuIkwTcxc6iNr00ETfthmIU=,iv:5HaDcLUloiTrkGeKDqSk/CFYrjPpeGhIj6RW5pMJioI=,tag:hfTHR6U7DMY32Dl1DurVKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFakpVUWIvQ1M1RndPMkdH
            L3ZXRmpuckFSWk1EeE0xeDljbGlzRjYwamtZCnk1TDFscWx6ano1YXpscVUwU05k
            TVRPUHo4RXE0a1RpbnpKVUxKcTBkRlUKLS0tIDEyQTlPTWlvbWpMT2ROQnIvbXBE
            TWMyZjdpcm5kR1BtYmZWVGhKVlp5L3cKZkMXZw5E5SlOmI3fRv7WgW+cXarVZ33L
            w/A3kht3qyX3fI55/0NbcdEQ/rC2zLufKpVyNbK5obHVf80yOqpNBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T10:20:56Z"
    mac: ENC[AES256_GCM,data:PwXQMSoHm+Hl8O+96zUM3zSgB1BY8VYmQhMk9ojiEo3iHWf09r3wIw+9fj+Dizfa+Ty4sFusAMg1D+7yriibUFH+bkwl6Oj9VDOFImhytHJe+csiIc36Dq8AcXheYehcEpg0SaCs9BSaw2Z/3Y76SZA9TVs5ekUrx9sOgPtHbCM=,iv:aHQODWRCKWLfjZS4ewtt/B+rmOodlNOpm22/PSzz7M0=,tag:lW9ZImFl6MzSQnHi2XqcGA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.9.4
