kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: cross-seed-secret
    namespace: media
stringData:
    xseed_api_key: ENC[AES256_GCM,data:JRgZ/R3NZQXA9//Pq/ScSrIpS5q3DFAj,iv:2e9mt/OlAlEDsEwOhGCRwUuTuBRUjujUi7+nnMo62M8=,tag:ZYp6pqTgC/wz8r0gRQQLAA==,type:str]
    config.js: ENC[AES256_GCM,data:tVmJYRaFaN0/CLKSd3gKR+zTu+iY6n4z6TqRqOQyK1hDVlsvkMY9A2OBvOzPoYnEYyzlJkaIiHwbTMHSDuDvTgfihb8UrJcEWOaMk7Dd+HOlUmdZkyanIw5jwnTn2ZeyAFLsZdfZTBdRlxqt8hp3yUmHzSZaxwWo0OvKND+bYdSFkUICKk+Oif5RGx9+tCtK5W4An0HTjXO/kVpSc3vznDYhR+2tqqfknObnUitPjmL2ejJ00ySpuxW9s5lKjffyWaWbF/9cxKdmxm3NExbWxRKMEC2CZBOjAPf5giE5SaNdqP9WslOIsQBKSV5ue5/DFYBVmnQ4xfvZ/RegoejPxgqtoIC1QKQSweknLBcrEO67qPB6md905rIv+B/sdwDZmFFdZJps5VqC9N179vyeCRPcl7No3l0K4u/QoD6uPCqImIeoIcKfO+JK1Y1GRC8heYC9mb3QBw2Xlvf/9XrXLn7HXgxTusjnSAOnr+ygWU7O4N7y24PGmPuQNuhMED2w+9Sg6DzYL05AXeQhE8hf6sq/5CfE3R5d0+X56+yBCS45sJMgUG7Jxp8t5z71TtPWVJZSsqMSc4EUVyEfN8VEEOReoSGP9O7adra8/DbCBu+i13Yy+GqKTM37KlB/ciXC0BASMc6dKwBP5br6x+UR41xE5QvrRTyBB5rra2q/cEBFQ2pMqjp1JVwhPRPS1H99d752P3VopR6tNKN4MhLxQbBRQegBaJh27Lz4PxiWK0tSOZKvjBGVoOzR15ffBgVc8Ig9OBE8Ll4wvQoXTxAG1EDe08PYjc6IQKV73ukqNhb5/LPPyjlfMeCPOUl5pAwQ1pS/Zk/JeJFqYCV9bqd1Yu0QZp/x4rQOgsih0GGjsjtU136m2HEtiNhffKZIRaJ6ZBR6ACLqIhfaRncrOvcW10TQ41O6Ku+7Z+IqREko1Dy9lOeykRVRRvSm5zwTSIMXLtQxGGuFSJM/bU8fdAFYbaiu9jdrOmHkiui82f0ws212fovXz8DFpSmQXAlQJY2sEEcVB2faqMSJgG4c7RIp3wKUXEZeQmEg/NRS8A6AG6wykcd2Njyv7ebzwtsVv/XWg8ACUCLXs4VaJvHtoSPYjjCo8uFaum6miQqvhhhOz7Kgpx91+h0/UFzYRUx4onMPko2QwSGO2i0EQ7fnEbE7u8VfOgk5V1fDWMB5wpDxdgjaaui+iEgfem6XjqxQ1+uY5m3OS3pg06W0vS9ENxEzFUgM3hxn/VD8ssZRExuuYSbyC4AbWhX7cH9V9YW/voFFHuhxqDf1GUMud3pkzw==,iv:MmYEh7lLOHKxDcWGf/OXmaR/MK7vxkIjPyBySX+1uWE=,tag:ik5DhNw7AL5Zk5PrwbDs3g==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RjV1SjZ4VkxGbTBreGZ5
            QjlrdW5ub0hieEVucVRudTZ2Y0FiYm5MQ0VnClRrQmNiVjJ4MFlpUnNubjI3Vnp4
            YUd3UEhtRXhndEg5SlhkWW5xT1lldUUKLS0tIDMySGRpcU4ycnJBbjFuais1dWs4
            KzE1ellIUytUcmtEZGN1eDZrZ3oybzgKTxQhAuu1JLHcSlk8RkqaJFi2oxneJG5m
            moOkiZD1qPFC0jyQNiZNGBhgMDyYcUZpDqgB9i3Me434SiLuaP6Hsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T05:49:42Z"
    mac: ENC[AES256_GCM,data:9st5pvuW83aQs8vRLnvZ7YCJhTyMlZ3PAwFJCoAaUA02FaNiyLRat6cRCrr26+M79UmUXRVDsYxQedVWT2mtoPXCeHoTHGfhiuQfTq0qF7FnJ/jifgCZV33sCQg+7yk2kpO1w13/nF1MXDH2ym2toOajaBkv1uEJjZM4dK382q0=,iv:McxwFlwqD5/klhRQV47kXmNJpgcfS6VeqOBLmv9/t8U=,tag:MDJYwJBz+BrtqN4fVcz52w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
