kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: kopia-nas-backup-secret
    namespace: backup
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    AWS_ACCESS_KEY_ID: 001584812a7ed590000000005
    AWS_SECRET_ACCESS_KEY: K001zpyGGePP3mt5v/vFFxfWAWVzySw
    KOPIA_S3_BUCKET: kopia-nas-offsite
    KOPIA_S3_ENDPOINT: s3.us-west-001.backblazeb2.com
    KOPIA_REPOSITORY_PASSWORD: Abk%Vx89LEYwJ%fc#g9BGsB6jT%rEmRhE*y!8aZLsySx9Ryr
    HEALTHCHECK_URL: https://healthchecks.peterson.com.ar/ping/cedad55d-e868-4b25-bd1c-6a0166f6eb1e
