---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &ns backup

generators:
  - secret-generator.yaml

configMapGenerator:
  - name: kopia-nas-backup-scripts
    files:
      - backup.sh=./scripts/backup.sh

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
    version: 5.0.1
    releaseName: kopia-nas-backup
    namespace: *ns
    valuesFile: values.yaml
