kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: kopia-nas-backup-secret
    namespace: backup
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    B2_KEY_ID: REPLACE_WITH_B2_KEY_ID
    B2_KEY: REPLACE_WITH_B2_APPLICATION_KEY
    KOPIA_B2_BUCKET: kopia-nas-offsite
    KOPIA_REPOSITORY_PASSWORD: REPLACE_WITH_KOPIA_REPOSITORY_PASSWORD
    HEALTHCHECK_URL: REPLACE_WITH_HEALTHCHECK_PING_URL_OR_LEAVE_EMPTY
