kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: kopia-nas-backup-secret
    namespace: backup
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EBC2O6tcMqsCYelNZDzmHr8nuCQHvfsvVA==,iv:Xde9z7TxicF+GIrGkOSDdiWsKXC0ssT5IVMkAx9iKj8=,tag:7hcV2FuKE+ny40huFHplPw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NMByAul/oSdtnRzKznKBlXbOBTDxZxtvz6NJ9bS3hw==,iv:Ty0B0d6QSpcw8ujdv9Sjlmpx+t2MsAK3FM0xOxIPjU4=,tag:9A4vP9oRdGrm+nXaQ6rYFw==,type:str]
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:ATitaHFvJJ5uUL/l4JUqJMo=,iv:h3FusNQEhHsOBKbjI1X/sA7vzFOLtTfKUIfAo45T5lE=,tag:As52yLjLIjl6rNQ7NbDMKg==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:qy3m0nbAkdzTCeNwArI5SHlgWHvYi2GV8w6S3UHS,iv:BIppeS7NN26+mitybco3uL1ZVCLk6xL/l4lv8CjVcwk=,tag:6VDHSXYUssJ+PkFV74CJSA==,type:str]
    KOPIA_REPOSITORY_PASSWORD: ENC[AES256_GCM,data:+hh+C4zwZufco+nKaO1BfnywdbDTUTEL/W+Ktj4PQoei8VLsONesizvsGnEhHlc1,iv:TaO4l0GFEmGHJzGhOWPkoBF3kEcceXEMbSyMRu+1Hkg=,tag:1z2SEEVI7kl931XjOLNGmw==,type:str]
    HEALTHCHECK_URL: ENC[AES256_GCM,data:BBEN89zuDnajGXUph2gAEfkkc8Bk/X6a4CI1rDSpLzM83bjiHozpjyNWPKIm2cs7bxUr7bofqedpaW7Fe1o64pocoyak4QEboVJQymiN,iv:GYTv2Efu9YnQAOIdsGIQA1PF7G44r75DIFCFRmwmb/c=,tag:PcLZhRGG66iw/D3z82ORdg==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TnMyZUJEeXhSbmp4Unpt
            QjFJeGpDWlJqa2phcmxnMG9EK0ZwZTZpajJJCjA5UXJrTDUxb2swM3FGL1BQcGhY
            ZWNpUWlwRG9CRXQvOXZrR0JSUk5CVWcKLS0tIFc1SEQ4UStMM0hkeWVLeUNZWjly
            K3BZY1NHdUZlcWJFNEpUTVhYNHBsUUkKV/Ylq/EQ7sW2FsrXvJQQZpb8u9APJNmH
            +mDnD3qJ+WhnnmD0EQ2xxEBHdqmg068kQGNaimlqqaPHj6W1NmV1MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T15:37:09Z"
    mac: ENC[AES256_GCM,data:tGtPNQ2nl05QJcHN8RUpVCu6KaXLOW7JQ/F8+hOGbjuze7zQ5YXiH44RYYbyXGddN5+wKp0p0Z4uKsK6/kanjhymELcwxP6hIGJhZMeKszlNVOqrz4f0CR0w1LVMvhlWL/pLTjewo+JUG1HjnWIFPROVwS1dWTR1/2HzqQyYUFY=,iv:/dy0ha8YibrgHiFREVQ+SHpn6iVVEpXpittQwmpxkgw=,tag:nCdlv6m5nft1AqQOEvILuQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
