kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: kopia-nas-backup-secret
    namespace: backup
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cW8dj5x+b8W9fSp43nQvsk1Zy+PQ52NoFw==,iv:eWPUxrhpSsdPX7rH7RnRtweya6UJ9rGZtMbkTRd35gA=,tag:yBPoTBf6Rk/4NCMTR4NGNQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wQHd/71Stl1Gy1xWz4cw/XAVJKYcLUZD9JNlDd+rBA==,iv:+Bsf5CS0bcK9aV9Hza6kA5qyufnLTWYRmFzAIm0RjwM=,tag:Foa2YPJ4msV+nwLi3MZ8LA==,type:str]
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:ATitaHFvJJ5uUL/l4JUqJMo=,iv:h3FusNQEhHsOBKbjI1X/sA7vzFOLtTfKUIfAo45T5lE=,tag:As52yLjLIjl6rNQ7NbDMKg==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:qy3m0nbAkdzTCeNwArI5SHlgWHvYi2GV8w6S3UHS,iv:BIppeS7NN26+mitybco3uL1ZVCLk6xL/l4lv8CjVcwk=,tag:6VDHSXYUssJ+PkFV74CJSA==,type:str]
    KOPIA_REPOSITORY_PASSWORD: ENC[AES256_GCM,data:XWYhu2SNkvdkKdJWejc1Xh+GDYa7Hq0FvZuzLCUawRv0LFbh1021sGhI3Gw996ny,iv:KXdQ/ny/gBTazvEquDUyNKE4CjCgLX3Yi5Uc2Uw65eI=,tag:krtGm38lRQEt+zyLLvhd4A==,type:str]
    HEALTHCHECK_URL: ENC[AES256_GCM,data:jSUjgXRw4Ztk1VWzK5EMCVVKTMdC+p91OCl7Aoz1aByGtkuXd/SCV30/UIVpjFNaVc+KTh1Pnl41FcePqmiBi3695HAGK0ZceeKdSVpH,iv:Z6Ly0OpxkAE4rTjDm3VuFC/yoJk493ROJvyqz+vy6hg=,tag:aVlpqs5F4PB/5sAqKK43Ag==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TnMyZUJEeXhSbmp4Unpt
            QjFJeGpDWlJqa2phcmxnMG9EK0ZwZTZpajJJCjA5UXJrTDUxb2swM3FGL1BQcGhY
            ZWNpUWlwRG9CRXQvOXZrR0JSUk5CVWcKLS0tIFc1SEQ4UStMM0hkeWVLeUNZWjly
            K3BZY1NHdUZlcWJFNEpUTVhYNHBsUUkKV/Ylq/EQ7sW2FsrXvJQQZpb8u9APJNmH
            +mDnD3qJ+WhnnmD0EQ2xxEBHdqmg068kQGNaimlqqaPHj6W1NmV1MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T15:54:39Z"
    mac: ENC[AES256_GCM,data:xF7Zw9QLpN07TjxN7W5Z4TPfXaIUGQGoyZcGNcgJbX82lYWf8w3d5ftFV2yISGhQbHePI1UUIkek+48nKVjwhhTxC5bpDWEdf7meAwnjM18kwJm45vAnQo+Uin2yIH1KJm2oVzd/iIMN50q+xAETM57JkXyM0A1/FSpIp3sXe98=,iv:bO33TzJ47k4MwxqbnZDxOasQa0Oo4+tnDkihLZn6BNY=,tag:JzgaEDKxpa3N5YIkhlIV1A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
