---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-configs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/infra/velero/
    targetRevision: main

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 11.1.0
    helm:
      valuesObject:
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.13.0@sha256:0b08ec0d150424fa914487e6665d7c84fff0c6a8eca76a23fa6d09e621d36d8a
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        configuration:
          backupStorageLocation:
            - name: cloud
              provider: aws
              bucket: backup-talos-proxmox-cluster
              default: true
              accessMode: ReadWrite
              credential:
                name: velero-credentials
                key: cloud
              config:
                region: us-west-001
                s3Url: "https://s3.us-west-001.backblazeb2.com"
                checksumAlgorithm: "" # required for Backblaze B2

          volumeSnapshotLocation:
            - name: democratic-csi
              provider: csi
              config: {}

          features: EnableCSI
          defaultVolumeSnapshotLocations: csi:democratic-csi

        schedules:
          daily-backups:
            disabled: false
            schedule: "0 1 * * *" # once a day, at midnight
            useOwnerReferencesInBackup: false
            template:
              ttl: "240h"
              storageLocation: cloud
              includedNamespaces:
              - '*'