---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-daily-volume-policies
data:
  policies.yaml: |
    version: v1
    volumePolicies:
      - conditions:
          nfs: {}
        action:
          type: skip
      - conditions:
          volumeTypes:
            - emptyDir
        action:
          type: skip
      - conditions:
          csi: {}
        action:
          type: snapshot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-weekly-volume-policies
data:
  policies.yaml: |
    version: v1
    volumePolicies:
      - conditions:
          nfs: {}
        action:
          type: skip
      - conditions:
          volumeTypes:
            - emptyDir
        action:
          type: skip
