kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: velero-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:OLR5Qo0nlfFhhCoYsTv/1NEO5GlC6UecnGb8T/mogtp0fyaDYJwAQkoNEtF847A2y9ha7GYRyVGdrsrbXdAKgZ9y2Z+RHKW3jsSf08VHdNJUk5Vexf1HlQB1nSXJ25GCxq2HKzt/w0uzxKc=,iv:tlxB0ENVZTlvMuyG/YsumYPu49h3Wg/3biO42AIBNU0=,tag:iC4sJSyb8UdbFR70SaUeXw==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZDAxQ2l1Z29HVjdhV0pl
            TlRIb09CQTM2a0tnN0RTc3RIdkpXenc5MlNFCnQ3bDY3Zk5GU0Z3RXZDa3loejg0
            SDlESFhGYytXRk8zRElVNDdsRlFjTTAKLS0tIGNwNzlyd2MwWDRYa2V6bVVGU1hh
            RnZvWHI5STd1SlNZZG16Y3JMdWh5LzgKjyIUQyNlgb2BOX3JBv9oaANRbEkNuOoX
            oOEpFgx6g1x4CyWYlc5rEIk2pINVhtXNxB3rbxjBpIncB0wOYlVZuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:42:03Z"
    mac: ENC[AES256_GCM,data:f9ivhC1rI+zHHeBOFbN46i7RX6UWG44OnHWrAzOWlhemRmjTBsa8Ulqd6FtE1/WNMabMPxtkfbI0Kq0zB4+miMMqVJNogORrMWU6SbY9Us02hJp7/MPx8CUR8HLMRXvKzbDzswYC5t0J+aABuG7rTzXk6TG8B4UIyrGX65FDrpY=,iv:nsmBtiPjZZ0myD+JQ0nd55smFyF1xBz4xQvBaPIJlhQ=,tag:BMrAnP5sA423BqGMRB8IkA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
