---
- name: Get pending updates for VM-{{ vm.key }}
  ansible.builtin.command: >-
    pvesh get /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.key }}/pending
    --output-format json
  changed_when: false
  register: pending_changes_response

- name: Reboot VM if changes pending VM-{{ vm.key }}
  vars:
    changes_pending: "{{ pending_changes_response.stdout | from_json | \
      json_query('[].[pending, delete] | []') | length > 0 }}"
  ansible.builtin.command: >-
    pvesh create /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.key }}/status/reboot
    --timeout {{ pve_vm_restart_timeout }}
  when: changes_pending
  changed_when: true
