---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &ns ai

resources:
  - static-route.yaml

helmCharts:
  - name: ollama
    repo: https://helm.otwld.com/
    # renovate: datasource=helm registryUrl=https://helm.otwld.com/ depName=ollama
    version: 1.55.0
    releaseName: ollama
    namespace: *ns
    valuesFile: values.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: ollama
    patch: |
      - op: add
        path: /metadata/labels/velero.io~1exclude-from-backup
        value: "true"
