---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ollama
  namespace: ai
spec:
  parentRefs:
    - name: internal-gateway
      namespace: network
  hostnames:
    - "ollama.lan.peterson.com.ar"
  rules:
    - backendRefs:
        - name: ollama
          port: 11434