apiVersion: v1
kind: Secret
metadata:
    name: external-dns-internal-secret
    namespace: network
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    tsig-secret: ENC[AES256_GCM,data:L9GqE7ZXuAy8RLWvVvS/4je58xR8oHanc8BZFWvnf5bnRUlssbJsiKi7ujk=,iv:YNmjIPOEoPIGIuMMa3/jqw581Kx3CV570TqONPKHBgI=,tag:U2l/Fij173sqHrCk2qSPNw==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWjdFT0dkRWtULzdZdjlB
            STA1RWVsUWJqVHVkYWcxeGE0a0RMYjBIM2w0ClRxamUyUklmMmhzcDBiU1EzdDlJ
            Ull0N2l4emtnUFdkRTlSZGg1Nk9ZdEEKLS0tIHVTTU5LNTVoSWNROGlNbDhOUTdu
            SGNWYnM1S2JDVG9LRHdjNzhHRTBVVkUKOM4Y3hIY7VtVDW8sI8JjzPr8LVxj6Tuv
            7nQhUhedyXFSetSvAiopItkiqo+IDd7/1GYREa7f9W7KwbKQgQUB0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:51:54Z"
    mac: ENC[AES256_GCM,data:3LOKimdF3xN8j1caaIrlDX3A8JHUr4dddOpsZBtx+4AtIaQGmkd/sUHt9yM9WLOHRcOOQfs1yv/PqCvKRdbVI8HR+BQN/Qyz2d5hPQPQkj0JC5PrJP63QTV1FchWIXtPX9gBHp860Q/3CQ1u9SXGyznbe0loUyKP+WHZoOybVcc=,iv:4sJwgkRcy1jfr+J67pxklcXo+eJfqMcfMpFCibTYXOQ=,tag:xQzlo9KJfmMgn1UdnMtXbA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
