apiVersion: v1
kind: Secret
metadata:
    name: trek-secret
    namespace: selfhosted
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:v5MsLFFg2yGEqG4BDJOn7HR2QSCFeSx77iDzdsapPhMz9wTc26Ll/1rmOl0s3DawipUoq69fspf+dnI2EKP2Ow==,iv:Cx7agTYpS3jck/oYVeUXru72xeM15IxJFhqroQzrhAI=,tag:ouQWRGytbaUxKFsWp//rbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MGFNUW5aV3AyOW85RDR6
            MDl5VmJXbmhOMDVjMENDREdIdXlkcjkwUGlzCkZhQnFNdjNwTk1mOC9oZ3FST2NV
            YW54TFRqM1JpT2tLVU1vZlBqNG9jZHMKLS0tIHZDRkNMSmRwOUsvZDUxUlBpTmNK
            eitLTEZwM2VuS1JXeWk2THNSSWxKZVEKQJSOavAOunm5NUlqk3nnx/YYYQj6fCJU
            KYCeOaEHwmQycEJQ+4iPZfbEs6+GhFTOHbSyzZVzWbAWEetxgRMTwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
    lastmodified: "2026-09-20T10:15:26Z"
    mac: ENC[AES256_GCM,data:3nu0Dh5kop28KMKTVXXP9bGaouYsGcIruC3ECZ7lKVq1Io/FclzxFXedE8pqkggwT7VEQPb9ixxdPViZXB4RiRYDuMCqmdavJH6SbqUzENenBWQ3pIG1dQnsb0rUp3hExoX5vEw4Emi5L4CPGlTipu2pBfkRmKh2R11DOoqLqCY=,iv:9wwMvGEFZbkhoADytCEhSEyBfte4wWfwJVojxmhDOe4=,tag:JrTwQlKukmkBWbtTaEIt/Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.13.3
