---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuppr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=ghcr.io/home-operations/charts depName=tuppr
      value: tuppr@0.1.3

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true
  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/infra/tuppr/
    targetRevision: main
