---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuppr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true
  source:
    repoURL: ghcr.io/home-operations/charts
    chart: tuppr
    targetRevision: 0.1.2
    helm:
      valuesObject:
        replicaCount: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuppr-upgrades
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/infra/tuppr/upgrades/
    targetRevision: main
