---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &ns system-upgrade

resources:
  - upgrades/health-check.yaml
  - upgrades/talos.yaml
  - upgrades/kubernetes.yaml

helmCharts:
  - name: tuppr
    repo: oci://ghcr.io/home-operations/charts
    # renovate: datasource=docker depName=ghcr.io/home-operations/charts/tuppr
    version: 0.1.3
    releaseName: tuppr
    namespace: *ns
    valuesFile: values.yaml
