---
- name: Setup workload backup schedules
  when: inventory_hostname in groups.get('pve_main', [])
  ansible.builtin.include_tasks: setup_backup.yaml
  with_items: "{{ pve_backup.workload_schedules | default({}, true) | dict2items }}"
  loop_control:
    loop_var: backup_config

- name: Setup host backups
  when: pve_backup.host.enabled | default(0, true)
  block:
    - name: Update backup script for host
      ansible.builtin.template:
        src: templates/backup-vehost.sh.j2
        dest: /usr/local/bin/backup-vehost
        backup: true
        mode: 0700

    - name: Update backup systemctl service
      ansible.builtin.template:
        src: templates/autobackup.service.j2
        dest: /etc/systemd/system/autobackup.service
        backup: true
        mode: 0644

    - name: Enable autobackup.service
      ansible.builtin.systemd_service:
        name: autobackup.service
        enabled: true
        daemon_reload: true

    - name: Update backup systemctl timer
      ansible.builtin.template:
        src: templates/autobackup.timer.j2
        dest: /etc/systemd/system/autobackup.timer
        backup: true
        mode: 0644

    - name: Enable autobackup.timer
      ansible.builtin.systemd_service:
        name: autobackup.timer
        enabled: true
        daemon_reload: true
        state: started
