---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app sabnzbd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@4.6.2
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/home-operations/sabnzbd
      value: ghcr.io/home-operations/sabnzbd:5.0.3@sha256:53064020792b2e21305c892c11aaa1eb32af2141cbd59119b52df226d664cd05

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/sabnzbd/
    targetRevision: main
