---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd-configs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/sabnzbd/
    targetRevision: main
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-3.7.3/charts/library/common/values.schema.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app sabnzbd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.1
    helm:
      valuesObject:
        strategy: RollingUpdate
        
        controllers:
          sabnzbd:
            replicas: 1
            pod:
              securityContext:
                runAsUser: 65534
                runAsGroup: 100
                fsGroup: 65534
                fsGroupChangePolicy: "OnRootMismatch"

            containers:
              app:
                image:
                  repository: &image ghcr.io/home-operations/sabnzbd
                  tag: &tag 4.5.1@sha256:fb8b35e47db0c5e03bdc3068476504dbc0ca47298a746718a139f52fab000993
                env:
                  SABNZBD__PORT: &port 8080
                  SABNZBD__HOST_WHITELIST_ENTRIES: >-
                    sabnzbd,
                    sabnzbd.media,
                    sabnzbd.media.svc,
                    sabnzbd.media.svc.cluster,
                    sabnzbd.media.svc.cluster.local,
                    sabnzbd.lan.peterson.com.ar
                  XSEED_HOST: cross-seed.media.svc.cluster.local
                  XSEED_PORT: 2468
                  XSEED_APIKEY:
                    valueFrom:
                      secretKeyRef:
                        name: cross-seed-secret
                        key: xseed_api_key
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /api?mode=version
                        port: *port
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes
                resources:
                  requests:
                    cpu: 5m
                    memory: 1024Mi
                  limits:
                    memory: 2048Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL

        service:
          app:
            controller: *app
            ports:
              http:
                port: *port

        route:
          app:
            enabled: true
            kind: HTTPRoute
            hostnames:
              - sabnzbd.lan.peterson.com.ar
            parentRefs:
              - kind: Gateway
                name: internal-gateway
                namespace: network
                sectionName: https
            rules:
              - backendRefs:
                  - name: *app
                    port: *port
                matches:
                  - path:
                      type: PathPrefix
                      value: /

        persistence:
          config:
            storageClass: zfs-generic-iscsi-csi-xfs
            accessMode: ReadWriteOnce
            size: 500Mi
            advancedMounts:
              sabnzbd:
                app:
                  - path: /config
          downloads:
            type: nfs
            server: nas.lan.peterson.com.ar
            path: /nibbler/media/library/
            globalMounts:
              - path: /data/downloads/usenet/complete
                subPath: downloads/usenet/complete
              - path: /data/incomplete-downloads/usenet
                subPath: incomplete-downloads/usenet
          temp:
            type: emptyDir
            advancedMounts:
              sabnzbd:
                app:
                  - path: /tmp
          scripts:
            type: configMap
            name: sabnzbd-scripts
            defaultMode: 0775
            advancedMounts:
              sabnzbd:
                app:
                  - path: /config/scripts
