proxmox:
  children:
    pve:
      children:
        pve_main:
          hosts:
            pve-01.local.example.com:
              ansible_user: root

        pve_secondaries:
          hosts: 
            pve-02.local.example.com:
              ansible_user: root
            pve-03.local.example.com:
              ansible_user: root
