---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app kromgo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@5.0.1
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/kashalls/kromgo
      value: ghcr.io/kashalls/kromgo:v0.10.0@sha256:965ecc92d68dc1a4a969397855367bbc70da03227a941ea607b73bb7e0b78fd6

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/infra/kromgo/
    targetRevision: main
