---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-config
  namespace: monitoring
data:
  config.yaml: |
    ---
    badge:
      font: Verdana.ttf
      size: 12

    metrics:
      - name: kubernetes_version
        query: kubernetes_build_info{service="kubernetes"}
        label: git_version
        title: Kubernetes

      - name: cluster_node_count
        query: count(kubelet_node_name)
        title: Nodes

      - name: cluster_pod_count
        query: sum(kubelet_running_pods)
        title: Pods

      - name: cluster_alert_count
        query: count(ALERTS{alertstate="firing",alertname!="Watchdog"}) OR vector(0)
        title: Alerts
        colors:
          - color: "green"
            min: 0
            max: 0
          - color: "red"
            min: 1
            max: 9999
