---

- name: Remove no subscription prompt
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/no-nag-script
    content: |
      DPkg::Post-Invoke { "dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ $? -eq 1 ]; then { echo 'Removing subscription nag from UI...'; sed -i '/.*data\.status.*{/{s/\!//;s/active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi"; };
    owner: root
    group: root
    mode: '0644'