# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
---
radarr:
  movies:
    base_url: !secret radarr_url
    api_key: !secret radarr_apikey
    delete_old_custom_formats: true

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-uhd-bluray-web
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-uhd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb

    custom_formats:
      # HDR10+ Boost - prefer HDR10+ releases
      - trash_ids:
          - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost
        assign_scores_to:
          - name: UHD Bluray + WEB

      # Movie Versions
      - trash_ids:
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: UHD Bluray + WEB
          - name: HD Bluray + WEB

      # Optional SDR
      - trash_ids:
          - 9c38ebb7384dada637be8899efa68e6f # SDR
          # - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: UHD Bluray + WEB

sonarr:
  tv:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_apikey
    delete_old_custom_formats: true

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-2160p
      - template: sonarr-v4-custom-formats-web-1080p

    media_naming:
      series: plex-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    custom_formats:
      # HDR10+ Boost - prefer HDR10+ releases
      - trash_ids:
          - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost
        assign_scores_to:
          - name: WEB-2160p

      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-2160p
          - name: WEB-1080p

      # Optional SDR
      - trash_ids:
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          # - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p
