---
- name: Get notification matchers {{ matcher_config.key }}
  ansible.builtin.command:
    pvesh get /cluster/notifications/matchers --output-format json
  changed_when: false
  register: existing_matchers

- name: Add notification matcher {{ matcher_config.key }}
  vars:
    create_params: >-
      {% for key, value in matcher_config.value.items() %}
        {% if key not in ['match-calendar', 'match-field', 'match-severity', 'target'] %}
        --{{ key }} '{{ value }}'
        {% endif %}
        {% if key in ['match-calendar', 'match-field', 'match-severity', 'target'] %}
          {% for item in value %}
          --{{ key }} '{{ item }}'
          {% endfor %}
        {% endif %}
      {% endfor %}
  ansible.builtin.command:
    pvesh create /cluster/notifications/matchers --name {{ matcher_config.key }} {{ create_params }}
  when: "matcher_config.key not in existing_matchers.stdout | from_json | json_query('[].name')"
  changed_when: true