---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-configs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/infra/alertmanager/
    targetRevision: main
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3 
    helm:
      valuesObject:
        controllers:
          alertmanager:
            type: statefulset
            annotations:
              reloader.stakater.com/auto: "true"

            statefulset:
              volumeClaimTemplates:
                - name: storage
                  accessMode: ReadWriteOnce
                  size: 300Mi
                  storageClass: zfs-generic-iscsi-csi-xfs
                  globalMounts:
                    - path: /alertmanager

            containers:
              alertmanager:
                image:
                  repository: quay.io/prometheus/alertmanager
                  tag: v0.28.1@sha256:27c475db5fb156cab31d5c18a4251ac7ed567746a2483ff264516437a39b15ba
                ports:
                  - name: http
                    containerPort: 9093
                probes:
                  liveness:
                    enabled: true
                  readiness:
                    enabled: true
                  startup:
                    enabled: true
                    spec:
                      failureThreshold: 30
                      periodSeconds: 5
                resources:
                  requests:
                    cpu: 11m
                    memory: 50M
                  limits:
                    memory: 99M

        service:
          app:
            controller: alertmanager
            ports:
              http:
                port: &port 9093

        persistence:
          config:
            type: configMap
            name: alertmanager
            globalMounts:
              - path: /etc/alertmanager
          secrets:
            type: secret
            name: alertmanager
            globalMounts:
              - path: /etc/secrets

        route:
          app:
            hostnames:
              - alertmanager.lan.peterson.com.ar
            parentRefs:
              - name: internal-gateway
                namespace: network
                sectionName: https
            rules:
              - backendRefs:
                  - name: alertmanager
                    port: *port