---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: alertmanager
    files:
      - alertmanager.yml=./config/alertmanager.yml

generatorOptions:
  disableNameSuffixHash: true

generators:
  - secret-generator.yaml
