kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    pushover_api_token: ENC[AES256_GCM,data:brKcaC74XA28I8T88I6E12Amk9nSVYoRsOAYVq9Q,iv:UMVeGy8g5euiWcqCs7/kFBwLyQFGyZYLDV/NV7lKiCk=,tag:Ea15axCWhjxqON8SL8vwWA==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:WIpYnemEVEHdL14fCqYXLKeXkd2OeWQEWfpb5UnQ,iv:ebhou7eb3nEofstp/o541gQH8peBfhQHjKATlvA5Xog=,tag:8BItDEMBOOKaeVvZX/ojKA==,type:str]
    healthcheck_canary_url: ENC[AES256_GCM,data:VjT390lCorwUzXQkKGAD+8xVcXisBgr4Qlt1U5RqCcgp3uc06PsNqzvq392Z/qyH4pzgfjnjGYWfAeZR55yxOc+k9tnRR/OdeBdHknf6,iv:8kJJE5dyZoXseB5j9fVC6wkMjuO2deHXqN13cyu9pC8=,tag:xl2DeVP0rhIB3J+iF1GUNg==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWSttdllZeWt6UmtBQ2Nl
            cjlEQjJ2SDVyOWpadUZ0bk5TTU1sb2plcTJjCk9rOVZ6MlZEYUtuLzBtVU1sd3Ru
            OFk0aVFDejRTeEgraEZmbWZoMlFGRUkKLS0tIHVsSGhtSjU1RVcvamFZNEFVaWYr
            aTJsYTV2dnNITUlXb3pzYnR4WEhmaFEKW5+Sz+Id7/zuiPoSWZ2Tzr25GaMgOCL0
            byeRDi7vp9XVlSXIpc3MdJxj4aFdZNfd306+vDih89Tn8FRCbD3c5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:13Z"
    mac: ENC[AES256_GCM,data:BHAcT8VnQGrge1H4W/mlpiEDtytVP0XjQdUx43Mst9v8pBf2vEsd0BUgI5z8iAsSEjR9T9gRIeirMIoTG5JSr/eMTHZmLjPqGktbKuNWgQFnhXpqGHdkOYnt50TxBLtROfOfgCnN3bDXAtUUh/D6Dq4WIGBKNqj0dEu5cBpeIGc=,iv:eHa/zp7vNAaDmov6pvngBRtl6LfTQwm7G2sNiH3+EWE=,tag:iGBn+pNwlPXC+HBCc0w2bA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
