---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://helm.cilium.io depName=cilium
      value: cilium@1.18.7

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: false

  ignoreDifferences:
    - group: ""
      kind: Service
      name: cilium-ingress
      jsonPointers:
        - /spec/ports

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/infra/cilium/
    targetRevision: main
