---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idrac-fan-control
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: utilities

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@5.2.1
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/tigerblue77/dell_idrac_fan_controller
      value: ghcr.io/tigerblue77/dell_idrac_fan_controller:latest@sha256:c09004039df6c468f225bbd2f711c538430e7d77de47ae4934fcf71ad61009ef

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/idrac-fan-control/
    targetRevision: main
