---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idrac-fan-control
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: utilities

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@4.6.2
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/tigerblue77/dell_idrac_fan_controller
      value: ghcr.io/tigerblue77/dell_idrac_fan_controller:latest@sha256:2017300d5fb34c9a6cac706dee43dec7a92ca27b2d8e4f8c87c1ba06b7d285aa

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/idrac-fan-control/
    targetRevision: main
