---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &ns utilities

generators:
  - secret-generator.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
    version: 4.6.2
    releaseName: pve-01-idrac-fan-control
    namespace: *ns
    valuesFile: values-pve-01.yaml
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
    version: 4.6.2
    releaseName: pve-02-idrac-fan-control
    namespace: *ns
    valuesFile: values-pve-02.yaml
