kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: idrac-fan-control-secret
    namespace: utilities
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    IDRAC_USERNAME: ENC[AES256_GCM,data:HSLoogoagQ==,iv:N4qTj/DxGguqxwhcfuwev25d1gHx4maaMGwdWnDjy9w=,tag:2np9hE06Nw5bB+XWLaSj1A==,type:str]
    IDRAC_PASSWORD: ENC[AES256_GCM,data:gTafGL3Okrn+5W85xQhQWQ==,iv:7IFNTyIUl1mkBFk4d7sfbbFvgOMdx0sNpKFJignfEDM=,tag:W0yZ+BVGhIlxvoBZxyU7wQ==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTjF6Unk0Y3JkaHNSSkhq
            SlpVK3QrbVlsOEpFYkErWFlQYXErOU4waHhZClFPaVQ1WkZKSXRnVk5oZTlMb2I0
            YTkwM2tZSzZEczF2eXhBN1JUN0RCZkUKLS0tIHlEOXZ1UzA1UDN0ZDRFdUd6VE02
            ZzZYVW1HOVdaYWdubWo2NU5hRGVEMGcKEFktKWffQZkG9w4LkxYzXKixILN/0b6w
            TmY9vhB8h4aQJWmWVjkoRr5hQni0mQisvMioj77siABJEkwogYrC1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:12Z"
    mac: ENC[AES256_GCM,data:xEX+Zp5sHEvQRLXidN/G6RbzcDPCAAZv4Z5CUC80O2cgfso3np4UJTsCF/vHWHxlKtZ6v/Iv4mzuh50q+GUQWmZv9yVDatJAbmVVVnpMYMkJoWOUT/lFWbxriqFLtDVcX7B4KjJF6zz+geQW3L8pf53io5uP10oFavUmWXxZZuw=,iv:Lk0VOiIOd5Dpjts00mbJzj0ugc1YtG9WPfh02jJLj4M=,tag:U+8xcmWfcmlBBxknXFkqFA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
