---
- name: Install nginx using apt
  ansible.builtin.apt:
    pkg: nginx
    state: latest

- name: Remove default nginx config file
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Update nginx config
  ansible.builtin.template:
    src: templates/proxmox.conf.j2
    dest: /etc/nginx/conf.d/proxmox.conf
    backup: true
    mode: 0644
  notify: Restart nginx

- name: Ensure /etc/systemd/system/nginx.service.d exists
  ansible.builtin.file:
    path: /etc/systemd/system/nginx.service.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Set nginx to start after pve-cluster
  ansible.builtin.copy:
    src: files/nginx-override.conf
    dest: /etc/systemd/system/nginx.service.d/override.conf
    mode: 0644
    owner: root
    group: root
