---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app tautulli
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@4.6.2
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/home-operations/tautulli
      value: ghcr.io/home-operations/tautulli:2.17.1@sha256:2183820d45a1413b4b8868fc18ad5eb9259630ea0151348cdc9cfb4017a0dd33

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/tautulli/
    targetRevision: main
