kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: paperless-secret
    namespace: selfhosted
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:LZ68yR9VRj86eY53Wi0TtU9Oh4htNw3pUqcYDnh1SyWe9cTD03ximgUZXSMUXaW6VJU=,iv:1Uip9hK16jsMhdyZ+Vutv8he9MWwJQS/pEqV4fBYS7c=,tag:smQEL0lnmRTAijzbaDXhrg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:amhK6h9MNqJ8,iv:1LG9DY1Ebd4wQt9Y2UurSwyekDRrQ6TfAfjdUKlsONk=,tag:FHDukr6LgoxUMvaJ6xHijQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:IHUOSgiegGyir+6+,iv:mdPzhb1cGjDaXuMoXW343amyzjD0XMEtJUZzWpDriTQ=,tag:zQwKRmYAI5PVhl5+fbKBEg==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINGFsUEhYMGRxUTFoTzFv
            NmIzWUNuNllPdzJaWUNFa2wrUVBDL1dNVlFJCmhZdzNSamNWZEpVeWJDK0VBdnNQ
            eTBLenQ2ZXpPalhyVDFrQWtoR2hucmsKLS0tIFNIR1REYXJhUlRScjVIb0ZNUU8x
            TW9GNWh1Yys3ZHh3NDA1YWxiSng3dzAKUFUBG4NB5ZgWjaFRi7a+xwQSY0ytrFT3
            swFh4asSPw+YCws/p/EQtGvUzBqzcKISIx5/aPPKM4nwEvAseJakJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:13Z"
    mac: ENC[AES256_GCM,data:1HvYbNF9gejS7fI5l5wK67o1dvkhM2K/EUWrVjMw7+IWHn9Vq/rBAgcLypbGby0BfKnoKWch5OEuKSQPZJVteQNeIcJ6ffqoSQxcqyOR3kozkhWuF8/K/Yd8hOtWUnqM4nz6N9tq2H19zqUloCJoRGBATukAdipPc640I5yQ2+k=,iv:U84eywxi8bMLr6zq6yYRP5g0y/kfeEx9gDQhp1yKKR4=,tag:kVV+uUDAjPBOpT/oeolDog==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
