---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: kopia-server-secret
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
stringData:
  KOPIA_REPOSITORY_PASSWORD: REPLACE_WITH_REPOSITORY_PASSWORD
  KOPIA_SERVER_USERNAME: REPLACE_WITH_SERVER_USERNAME
  KOPIA_SERVER_PASSWORD: REPLACE_WITH_SERVER_PASSWORD
  KOPIA_S3_BUCKET: kopia-server-offsite
  KOPIA_S3_ENDPOINT: s3.us-west-004.backblazeb2.com
  AWS_ACCESS_KEY_ID: REPLACE_WITH_B2_KEY_ID
  AWS_SECRET_ACCESS_KEY: REPLACE_WITH_B2_KEY
  KOPIA_OFFSITE_PASSWORD: REPLACE_WITH_OFFSITE_REPO_PASSWORD
  HEALTHCHECK_URL: REPLACE_WITH_HEALTHCHECK_URL
