kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: kopia-server-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    KOPIA_REPOSITORY_PASSWORD: ENC[AES256_GCM,data:4HA7vIT/FHlDzLzHNWxmoIeGZx5OeDFoPQxImOpqMMoz/QT7gyFX+9XBnm1PVLj0,iv:CZs3ms7ezclgXpSbLsu6M2aniq86McfE9GTk/5CKn9E=,tag:PzcWQuK+BdnyH+9gAofKzw==,type:str]
    KOPIA_SERVER_USERNAME: ENC[AES256_GCM,data:9rasg3oE72kn,iv:n8ACCD4h5Npnm1Z2e2D5/WVFGVMNfO9aUBF7KYa7HWU=,tag:K8fEklJsVxlaj9uZSDJqYw==,type:str]
    KOPIA_SERVER_PASSWORD: ENC[AES256_GCM,data:yWVKqZqXB4juzcXnNjQ=,iv:M24QJQbdOhNy7VJUHpBEJgW9WKxvjxi5r+T/hrvAxxE=,tag:rlxYzt0XAtmQovNcEC2hOg==,type:str]
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:AudBFtaGLk2JRzR2eedBgejP8+M=,iv:xCktBzHORwV1Alm9U1C5YqDawMZhh+3QdulnNJ0KT4s=,tag:0tj10Ty/S+YI8bZSlpOhhQ==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:F8Arxsw8q/cHlOFDVbSlad3MUBR8Sj5GUZRm7FXP,iv:9Pts2uM43GroDxNb9XzEQGEbveg2L0Y29CqnIfVuDJQ=,tag:Pi1mUVQMFeLEZizYJyxmCQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eNgpfgrd5q35tlz/feugpVxz4E1frcgm+Q==,iv:wC7uPS1frURyGi0cDypf3ZZ9Y2ab5axTKVsdBN5HeUw=,tag:SZZ0Ood6pqdtKsuz8PqXZg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DCdfA4ooqFCfg6VYwmg5b26OTJBhgZkHPBWs961x2A==,iv:HgdO6mMzZdsBmamvsNAzsFOC6V1lR2Ia16HnO6aHYC8=,tag:6P1ibZ78quY6G/iTWGdUMw==,type:str]
    HEALTHCHECK_URL: ENC[AES256_GCM,data:UuXedfV2LtM0acBN7BA2huJOjmcYCIc/Vhgi9wGVErpDFM6nkC3DGDOc/cP0wrB9yCsGWca8eIUM52GnZjlpf3pGeDXrhdRecYuvrn9w,iv:nF0xeJ+KqV366IHBNr36aYvEAYVKBXz37wLCq9xmwu4=,tag:v6NV0VMBfo9eHWQoFHiXxA==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpLzM1cGZBeVNEd2dCTDVo
            NU04NXc1NWxlTVkrQXJScmVUZWEyVXljVkNZCjlZT1ZtZUh4Rkxva3hySnVNL0ho
            UmtoelcrankweE1Sd2JYWjNUSTdlejgKLS0tIGhIeWREWHVhSFdRdzl0NFdhcEM1
            SWlmQ01DSktnWXpRS1drT1p2K05wTDgKvfCpK2MI8SsYlqEer9dtvxbeIBlKGLj9
            O1DLWoxYbZYt7cFlnxKg2qnLMC6BVWxer/YmAzDnqfawSIZ4ajD3Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T22:00:19Z"
    mac: ENC[AES256_GCM,data:tuCmUO2zzn658gbYYNav/YOWDbE3Z5RPyRXhZNM0o1cxyTySoCpaJXW2RKXOQcZS1liOVMNFLiI5G0NtVUobySwORr2+lYhbPqzfMPnmoePx0qLYEMEpfDOemH/7cALsagJ6tYaI4TYWhwQzkxGi0fS/0f1I/LT/g5MQM9l+vV0=,iv:FcjjGfkzb0wRuDYRpjegG+kAv5sd/RX5xppr8BvXzhU=,tag:OKwWVvl3rTRNC+b+xobsJw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
