kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: kopia-server-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    KOPIA_REPOSITORY_PASSWORD: ENC[AES256_GCM,data:QcmfOyFL2Ruk2Uej544r8e/eobgTauKN3NkKLBRtxY9OW0dGcdOhilHQTEyhosFN,iv:rdGlV7+YHzFGehwgr1xJ+V9bwUX9xv3BjSiqVaVe9r8=,tag:DFaVDP+hykdgh2GASPSD+g==,type:str]
    KOPIA_SERVER_USERNAME: ENC[AES256_GCM,data:9rasg3oE72kn,iv:n8ACCD4h5Npnm1Z2e2D5/WVFGVMNfO9aUBF7KYa7HWU=,tag:K8fEklJsVxlaj9uZSDJqYw==,type:str]
    KOPIA_SERVER_PASSWORD: ENC[AES256_GCM,data:YsQUOezrC66dJ50nfAY=,iv:tg4UbfV119McPu8WtiA8Yya80mebV9FiZ//VYJKyCMM=,tag:B52efIgVsiDv4T/YTIdYIA==,type:str]
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:AudBFtaGLk2JRzR2eedBgejP8+M=,iv:xCktBzHORwV1Alm9U1C5YqDawMZhh+3QdulnNJ0KT4s=,tag:0tj10Ty/S+YI8bZSlpOhhQ==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:F8Arxsw8q/cHlOFDVbSlad3MUBR8Sj5GUZRm7FXP,iv:9Pts2uM43GroDxNb9XzEQGEbveg2L0Y29CqnIfVuDJQ=,tag:Pi1mUVQMFeLEZizYJyxmCQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JqHdVZXVQPU7r75mdcRXxohT5poTHX9vEQ==,iv:uJfDzP7ExMaTwytr79ME3eDRQ4PEbG9jXIm4lBY9guk=,tag:YKZMx1JCocLD4DuF6igZqg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:axcl7Hg1ByO5FcBKvOpi/YGKe24tHpVwM7lJsdJAKA==,iv:eXstR6lDCu5S3aFgyTp5iC1hHwXHAceLh3VSjEvRqZI=,tag:ojmYfl+zU54lyo9bjDh75Q==,type:str]
    KOPIA_OFFSITE_PASSWORD: ENC[AES256_GCM,data:+ymCw9/s6DeX1hrJN+y2EWzkDbHeQIfgt89MhhB6zsfpEWx2mb4I77ArivPx0225,iv:wLF0d/z2WsUAoUck4Ou4pyhqABCzbYZaNZREzaAxDNM=,tag:IRvRSHBeSm3nKNWXvIsh0g==,type:str]
    HEALTHCHECK_URL: ENC[AES256_GCM,data:SIxFoomoSAz0RbRcGf9m3Wh7tk5E7qqAT8AkP0hTLAZ1WwgIp595GfJVlKh0b876jN+lvq2aCcH/Cyy8hnjF9R9NrEnkC7D0Kyld3ick,iv:v88Kno1tJv1EsAOPYf9aAr2IH77+4iApRXizjLfyY/M=,tag:g7av3TAKsjLgKNO4Wsu2fg==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpLzM1cGZBeVNEd2dCTDVo
            NU04NXc1NWxlTVkrQXJScmVUZWEyVXljVkNZCjlZT1ZtZUh4Rkxva3hySnVNL0ho
            UmtoelcrankweE1Sd2JYWjNUSTdlejgKLS0tIGhIeWREWHVhSFdRdzl0NFdhcEM1
            SWlmQ01DSktnWXpRS1drT1p2K05wTDgKvfCpK2MI8SsYlqEer9dtvxbeIBlKGLj9
            O1DLWoxYbZYt7cFlnxKg2qnLMC6BVWxer/YmAzDnqfawSIZ4ajD3Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:15:28Z"
    mac: ENC[AES256_GCM,data:fYplGC50S6fC+iVyMvFZEOaYqMFkgNvJRSxiFMxsJFfIZp7XeA/BPjSQ7iImR3XnIggc4qG1iDHzCEmIoMT88/ghWDQQ5BqM7ODydBK3qvvdPIZXBtz1Kr6JOrKSo85ziB8oQbNJsJqn85ro7hJrG082GcvyMaicesp65OKgnj8=,iv:+jF3LRpTBpcWSdTWviQYxd/5sw1F4i7IqREkwQzoCiA=,tag:vfRYV2wYaGl43SwkTixjSQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
