# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-3.7.3/charts/library/common/values.schema.json
---
controllers:
  kopia-server:
    replicas: 1

    pod:
      securityContext:
        runAsUser: 65534
        runAsGroup: 100
        runAsNonRoot: true
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    initContainers:
      init-repo:
        image:
          repository: ghcr.io/home-operations/kopia
          tag: 0.22.3@sha256:17ab64542280197a5368247deaefadc3e3bbe15714ab666c2455a06824e86efd
        command:
          - /bin/bash
          - /scripts/init-repo.sh
        envFrom:
          - secretRef:
              name: kopia-server-secret

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/kopia
          tag: 0.22.3@sha256:17ab64542280197a5368247deaefadc3e3bbe15714ab666c2455a06824e86efd
        command:
          - /bin/bash
          - /scripts/start-server.sh
        envFrom:
          - secretRef:
              name: kopia-server-secret
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 51515
              initialDelaySeconds: 10
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *port
              initialDelaySeconds: 5
              periodSeconds: 10
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: ["ALL"]}

  offsite-sync:
    type: cronjob

    cronjob:
      schedule: "0 1 * * *"
      backoffLimit: 0
      timeZone: UTC
      concurrencyPolicy: Forbid
      failedJobsHistory: 3
      successfulJobsHistory: 3

    pod:
      securityContext:
        runAsUser: 65534
        runAsGroup: 100
        runAsNonRoot: true
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/kopia
          tag: 0.22.3@sha256:17ab64542280197a5368247deaefadc3e3bbe15714ab666c2455a06824e86efd
        command:
          - /bin/bash
          - /scripts/sync-offsite.sh
        envFrom:
          - secretRef:
              name: kopia-server-secret
        resources:
          requests:
            cpu: 1500m
            memory: 2Gi
          limits:
            memory: 4Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: ["ALL"]}

service:
  app:
    controller: kopia-server
    ports:
      http:
        port: *port

route:
  app:
    enabled: true
    kind: HTTPRoute
    hostnames:
      - kopia.lan.peterson.com.ar
    parentRefs:
      - kind: Gateway
        name: internal-gateway
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - name: kopia-server-app
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  nfs-repo:
    type: nfs
    server: nas.lan.peterson.com.ar
    path: /nibbler/apps/kopia-backups
    globalMounts:
      - path: /repo
  scripts:
    type: configMap
    name: kopia-server-scripts
    defaultMode: 0775
    globalMounts:
      - path: /scripts
        readOnly: true
  kopia-cache:
    storageClass: zfs-generic-iscsi-csi-xfs
    accessMode: ReadWriteOnce
    size: 50Gi
    labels:
      velero.io/exclude-from-backup: "true"
    advancedMounts:
      kopia-server:
        app:
          - path: /config/cache
        init-repo:
          - path: /config/cache
  kopia-sync-cache:
    type: emptyDir
    advancedMounts:
      offsite-sync:
        app:
          - path: /config/cache
  kopia-config:
    type: emptyDir
    globalMounts:
      - path: /config
        subPath: config
  kopia-logs:
    type: emptyDir
    globalMounts:
      - path: /config/logs
  tmp:
    type: emptyDir
    globalMounts:
      - path: /tmp
