---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app tqm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@4.6.2
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/home-operations/tqm
      value: ghcr.io/home-operations/tqm:1.20.0@sha256:1c26b5eae1b329b55449b2d1cf1411b1b623f9a15df3d8f5b50b7d1762e25579

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/tqm/
    targetRevision: main
