kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: tqm-secret
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    config.yaml: ENC[AES256_GCM,data:XFyHb/Ir/duP781Eln1XUU4JtgUm3Dik4wMn+cs2S22usrFcvO9WI9KB6zXeCVBfLG3J5U6x9HWvTkm/HYC9e3Eo5hTHlHNpv4eJeSaiw0/bSlcfICgO2czgOgzH/molAWFEmHpH3eeJpsCEbczQ58fHUToXwQxKjJJmJJKqZOdlCu5cbp0PmdJyYzaE0V0m+C/Cwvb8XwJsP8QUW+IEK0rLfdCHA9XdVmg70s3rvnkcTnlP7ORz2sQW+LkeLtawN9Lebljj0r8OFgKnvMsrIQNbVsed9AnCQf5H7x0f5k5TOoSa6s1oIGZHZ2/kAfqEhwmL6ysIdaIBil9EcP93QZqlYoYsP4D0Va/JlvNMQw7rJrJshNNBc/hFRYEH0MAKOdoaTm2StVbqvWvTYmFFUVjNLYJU1fPt51BnO2KujvjasffBdu2AYcL3FjHM1YlYTumY2r/VeCTy4J+lJrAEHg0PKn2ZqnaO1igPrl6tVt4PqFTVVrf29ZXL0aFEYBafDx1YFX1EffKJCjUPnDq/IiJFMUuDP4dt9ebZnb3ytMTVUSpH1olUXWYJ2pz9c4DejJKQ2PYn1NihnXL7NLDQrr+o8/qSwEJiMO0JcGkDw4qQ5pDmPpegrJYmkZXo2pVD5hsbW/yO0PPLgvvesmhdNM3j/4GnKkwqsVrjBaUjVz22g59ift4r3bFTMS1mOm4euOmeLulzaTpc+1MCn/PT0DyAh4oneO5RtuubWrvcEvy6tgdxErkK8sxt/EK+kDngwKPckH35/FaJ2GYBtAw1l+twp+QcN5Ncx958wPy31SSRZfilGWS0CsHCnvBzs96k0wgItBVv9R/oNabrs1DVoX6lcIMDHukz8w/K8wN4Bp2QwN+vG0jJv5TkMFDc629RBj6w/ioOWLrjOKS7v8L5xVj82wTrRTqaNY5lcbJT6ozY4AgIo+RL8eiut/6WjtGOFodbSuLepJajAbLD6Nv1aOaNO0V0Bzjif3f1dq5Hho6VoYyjdXFiiojWZD4l89VP4zAc7PrEVP99yxedRgTT7MKYtILKkUPikeJBfPx2Aryrx9B1GLhe8txcB1AzrYT3FmsgEOSNhc076VFVIVE7gjcF6+TCLb3OkWaUC2V4i+svVVRqho0nvBaLoifqHmFcI5EKpjDDtIxODnm/HnkHbAx0gl0KbV+ZPt/FfZNRZu0=,iv:E6E5yOV1J0ilZJxKLzh2Cn6stzP3XlRs0uiwCHXXAlI=,tag:kLqJXYdbXwA1WLHlSyUltA==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZkhvVGhDNVVheit3WEhX
            NFZwczBDNVVpMjJCaVcvdmR5cGhOMFpvWGhvCkVwTXl1T2FSeWdDMkhPc0JGVlRz
            WFZneG91ajVXZHVWWWtlTGJZaURudmsKLS0tIG9yK1c0T2N6dFlUcDFXUEwzQnJT
            L0pLQVJaRTkzb2kzUFNwaXpLUGRJR3MKRDwHU0CVdn+H5RYZq3USFUcBXYgIgtWm
            g1zXv8zha3y80NgDtqfYqsUhK3x0pLHHayClB09k1Oyv+HsZoNlFig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:09:52Z"
    mac: ENC[AES256_GCM,data:05HvCcH3v0jsdO68pL110BBl1Z0HYQhqmtiHRdW9plQqDn2pWcxazLzJCY3DjJ0V/X8SqkzaC9p53xNi/pI1Kmwz+5tTc3Jb1P9Ih5yWriYV9v1GOmwCg3Nm8u/J1RYAEEgqrIPoXORoWwfkPqNNFsz5yPeEfDfZYJMOVRG8PXo=,iv:8P1iUaQF2hhhUXdijbGqdXkqJLOpudbrMLcOx6Qh3l4=,tag:reb93IxFAPKMMI1GLRzKUA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
