# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-3.7.3/charts/library/common/values.schema.json
---
defaultPodOptions:
  securityContext:
    runAsUser: 65534
    runAsGroup: 100
    fsGroup: 65534
    fsGroupChangePolicy: "OnRootMismatch"

controllers:
  tqm:
    type: cronjob

    cronjob: &cronJobSpec
      schedule: "@hourly"
      backoffLimit: 0
      concurrencyPolicy: Forbid
      failedJobsHistory: 3
      successfulJobsHistory: 3

    pod:
      restartPolicy: Never

    initContainers:
      retag: &container
        image:
          repository: ghcr.io/home-operations/tqm
          tag: 1.20.0@sha256:1c26b5eae1b329b55449b2d1cf1411b1b623f9a15df3d8f5b50b7d1762e25579
        args:
          - retag
          - qb
        resources:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

    containers:
      clean:
        <<: *container
        args:
          - clean
          - qb

  orphaned:
    type: cronjob
    cronjob:
      <<: *cronJobSpec
      schedule: "@daily"
    pod:
      restartPolicy: Never
    containers:
      app:
        <<: *container
        args:
          - orphan
          - qb

persistence:
  config:
    type: emptyDir
    globalMounts:
      - path: /.config/tqm
  config-file:
    type: secret
    name: tqm-secret
    globalMounts:
      - path: /.config/tqm/config.yaml
        subPath: config.yaml
        readOnly: true
  downloads:
    type: nfs
    server: nas.lan.peterson.com.ar
    path: /nibbler/media/library/
    globalMounts:
      - path: /data/downloads/torrents
        subPath: downloads/torrents
