---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: ghcr.io/spegel-org/helm-charts
    chart: spegel
    targetRevision: 0.6.0
    helm:
      valuesObject:
        spegel:
          containerdRegistryConfigPath: /etc/cri/conf.d/hosts
