---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &ns infra

helmCharts:
  - name: spegel
    repo: oci://ghcr.io/spegel-org/helm-charts
    # renovate: datasource=docker depName=ghcr.io/spegel-org/helm-charts/spegel
    version: 0.7.1
    releaseName: spegel
    namespace: *ns
    valuesFile: values.yaml
