---
- name: Get ISO images Storage {{ storage_contents_config.key }}
  ansible.builtin.command:
    pvesh get /nodes/{{ ansible_facts.hostname }}/storage/{{ storage_contents_config.key }}/content
    --content iso
    --output-format json
  changed_when: false
  register: existing_iso_files

- name: Update ISO images Storage {{ storage_contents_config.key }}
  vars:
    iso_names: "{{ storage_contents_config.value.isos | map(attribute='url') |  map('basename') }}"
    existing_iso_names:
      "{{ existing_iso_files.stdout | from_json | json_query('[].volid') | map('basename') }}"
  block:
    - name: Download ISO images Storage {{ storage_contents_config.key }}
      ansible.builtin.command: >-
        pvesh create /nodes/{{ ansible_facts.hostname }}/storage/{{ storage_contents_config.key }}/download-url
        --content iso
        --filename {{ iso.url | basename }}
        --url {{ iso.url }}
        {% if iso.checksum is defined %}
        {% set checksum_parts = iso.checksum.split(':') %}
        --checksum-algorithm {{ checksum_parts[0] }}
        --checksum {{ checksum_parts[1] }}
        {% endif %}
      when: iso.url | basename not in existing_iso_names
      changed_when: true
      with_items: "{{ storage_contents_config.value.isos }}"
      loop_control:
        loop_var: iso

    - name: Delete ISO images Storage {{ storage_contents_config.key }}
      ansible.builtin.command: >-
        pvesh delete /nodes/{{ ansible_facts.hostname }}/storage/{{ storage_contents_config.key }}/content/{{ iso }}
      when: pve_remove_unrefenced.vm_iso and iso | basename not in iso_names
      changed_when: true
      with_items: "{{ existing_iso_files.stdout | from_json | json_query('[].volid') }}"
      loop_control:
        loop_var: iso
