---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: infra

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://charts.jetstack.io depName=cert-manager
      value: cert-manager@v1.20.2

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/infra/cert-manager/
    targetRevision: main
