apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: infra
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:R+SmkDoMrQgRUce9GNuD/EeHPDB8DbdL/7UbIFQI9A6GVThiKA==,iv:mpLfLOEB8hxhEQIycaQu5F/6c3JfOHs12P/M4F783t4=,tag:221sdFEQP6GW+H75q1VOyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWTRjNlQ5clUvRTVtVnRp
            WHltRk9QcUZsQ3JEV3FQVVJwS2cvaVM4ZEZBCnNmdEI4K0NLQS80WlBWV08wRldi
            MlNSc2F0bGFNaHZ1TC9tc3k1cDZ1T2sKLS0tIGRNc2gyOWlwUHllUGU3V0RRTklZ
            Q3MrbU05dk9DQ05hdk1Rd0ZjT2J6dHcKH+tSy9Y9A7hs5VHbhdlPJywK1k+kphZs
            lBNeTWh0wInE6p10UWb91gkurE90SpS5pvTwrI0GWLtpVJJ3Fw9kBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T16:46:27Z"
    mac: ENC[AES256_GCM,data:CQsCAfCltSZ3a1/TAdQTYcfYGhTECJs9HYZWcITxvafsVbQEDJHNFGCUIYH5z74v0jEv56dxgmShOSWAYEH0Dg6Rd7i1jsmGSuZ5BsuxAYCjNRydGa6ZPoUO053rVZinxOF0VsJy9TXIElP5oK8AxSEvttFIeKSbH9KiG6lN4D4=,iv:8XdSVO8XMdC2ZZSfEVn19G0lbBRPAsfwMPzP4wFB9JA=,tag:Mx2UUE/Md+MG8cEqcKZZog==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.9.4
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod-cloudflare
spec:
    acme:
        email: ENC[AES256_GCM,data:7bEfqBzFAhC+GACj9BCRn915G2JXKRhMaN5X,iv:d5l2SNLM+6H3ACJG4I2CzaR+kTjNClCPRKuDwUkzm8c=,tag:2WfoE11Wefc7XNfA0oRBAw==,type:str]
        server: ENC[AES256_GCM,data:cFHLA799ie0413bpkDuL+SHqVqDUN5np87zKQsyUmQjdci9QL+7eIBZ8dMHrkg==,iv:Spfkz7/oPLlVL29Hq5sck/T1v7nAfsllr9UyNATQ5Rk=,tag:bOiHGAXTA5l8zQgPJ5Ux6w==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:D2DmC7FHrRk8PfjJlv8soqkX2J4ZXbJ4vIsZ,iv:IZrUoNdOMfcKCpE2534QCx3H7zeBY932CpslyjS0aNE=,tag:VC7jaENrnFwoT7naAkxApw==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:ssovc2Rp0UatGbE8ht1ZeqtQndM=,iv:BZtxTuZsbubhOnUUK+Uj097b2SqEb7QKFssCpbHZMVM=,tag:GqWBsZoTaXLg+nDZ9vEXbw==,type:str]
                        key: ENC[AES256_GCM,data:HkVpX5btkjYU,iv:nkwjvMUpKP1ASBPoZteo/G5v3/PVbWAz0LNIsE+zYjE=,tag:OPW4r5IyGCki7fpcmgX6NA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWTRjNlQ5clUvRTVtVnRp
            WHltRk9QcUZsQ3JEV3FQVVJwS2cvaVM4ZEZBCnNmdEI4K0NLQS80WlBWV08wRldi
            MlNSc2F0bGFNaHZ1TC9tc3k1cDZ1T2sKLS0tIGRNc2gyOWlwUHllUGU3V0RRTklZ
            Q3MrbU05dk9DQ05hdk1Rd0ZjT2J6dHcKH+tSy9Y9A7hs5VHbhdlPJywK1k+kphZs
            lBNeTWh0wInE6p10UWb91gkurE90SpS5pvTwrI0GWLtpVJJ3Fw9kBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T16:46:27Z"
    mac: ENC[AES256_GCM,data:CQsCAfCltSZ3a1/TAdQTYcfYGhTECJs9HYZWcITxvafsVbQEDJHNFGCUIYH5z74v0jEv56dxgmShOSWAYEH0Dg6Rd7i1jsmGSuZ5BsuxAYCjNRydGa6ZPoUO053rVZinxOF0VsJy9TXIElP5oK8AxSEvttFIeKSbH9KiG6lN4D4=,iv:8XdSVO8XMdC2ZZSfEVn19G0lbBRPAsfwMPzP4wFB9JA=,tag:Mx2UUE/Md+MG8cEqcKZZog==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.9.4
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod-http01
spec:
    acme:
        email: ENC[AES256_GCM,data:7bEfqBzFAhC+GACj9BCRn915G2JXKRhMaN5X,iv:d5l2SNLM+6H3ACJG4I2CzaR+kTjNClCPRKuDwUkzm8c=,tag:2WfoE11Wefc7XNfA0oRBAw==,type:str]
        server: ENC[AES256_GCM,data:cFHLA799ie0413bpkDuL+SHqVqDUN5np87zKQsyUmQjdci9QL+7eIBZ8dMHrkg==,iv:Spfkz7/oPLlVL29Hq5sck/T1v7nAfsllr9UyNATQ5Rk=,tag:bOiHGAXTA5l8zQgPJ5Ux6w==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:wqL3m9dxVHQM48mQr4l6C9gY3lIHbBE=,iv:3xSmw7y2+ec/LdHkOSFtMDn4tc/Sh6h5ntKZQQXnlCQ=,tag:IA5eJpfBexdyM0x41fZ2oA==,type:str]
        solvers:
            - http01:
                gatewayHTTPRoute:
                    parentRefs:
                        - name: ENC[AES256_GCM,data:BqDPjtq/8ylHiLEhhr0=,iv:Uiq7B4XK00rSHG3W7bNwlmpXXT4GdvytoEADUY3q8yA=,tag:H8i8BsYm2d6NTHcRiNzpbg==,type:str]
                          namespace: ENC[AES256_GCM,data:3nChIi2RvLwQK88=,iv:ImxVwmoTdvPA7Yv7Tyd1P8osJrUT7l4bGSZIc9EeVks=,tag:XETHiJd/PwJn7Z3aF2C+dA==,type:str]
                          kind: Gateway
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWTRjNlQ5clUvRTVtVnRp
            WHltRk9QcUZsQ3JEV3FQVVJwS2cvaVM4ZEZBCnNmdEI4K0NLQS80WlBWV08wRldi
            MlNSc2F0bGFNaHZ1TC9tc3k1cDZ1T2sKLS0tIGRNc2gyOWlwUHllUGU3V0RRTklZ
            Q3MrbU05dk9DQ05hdk1Rd0ZjT2J6dHcKH+tSy9Y9A7hs5VHbhdlPJywK1k+kphZs
            lBNeTWh0wInE6p10UWb91gkurE90SpS5pvTwrI0GWLtpVJJ3Fw9kBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T16:46:27Z"
    mac: ENC[AES256_GCM,data:CQsCAfCltSZ3a1/TAdQTYcfYGhTECJs9HYZWcITxvafsVbQEDJHNFGCUIYH5z74v0jEv56dxgmShOSWAYEH0Dg6Rd7i1jsmGSuZ5BsuxAYCjNRydGa6ZPoUO053rVZinxOF0VsJy9TXIElP5oK8AxSEvttFIeKSbH9KiG6lN4D4=,iv:8XdSVO8XMdC2ZZSfEVn19G0lbBRPAsfwMPzP4wFB9JA=,tag:Mx2UUE/Md+MG8cEqcKZZog==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.9.4
