---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &ns media

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
    version: 5.0.1
    releaseName: qbrr
    namespace: *ns
    valuesFile: values.yaml
