---
defaultPodOptions:
  securityContext:
    runAsUser: 65534
    runAsGroup: 100
    fsGroup: 65534
    fsGroupChangePolicy: "OnRootMismatch"

controllers:
  reannounce:
    containers:
      app:
        image:
          repository: ghcr.io/buroa/qbrr
          tag: 0.1.6@sha256:50baeb6633f144b7220777c56a8d501ea708d43043e28eb416d93e4e96efe06b
        env:
          QBITTORRENT_HOST: http://qbittorrent.media.svc.cluster.local
        resources:
          requests:
            memory: 128Mi
            cpu: 25m
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
