---
- name: Get current status of container CT-{{ ct.key }}
  ansible.builtin.command: >-
    pvesh get /nodes/{{ ansible_facts.hostname }}/lxc/{{ container_id }}/status/current
    --output-format json
  changed_when: false
  register: container_status_raw

- name: Remove container if managed by ansible CT-{{ ct.key }}
  ansible.builtin.command: >-
    pvesh delete /nodes/{{ ansible_facts.hostname }}/lxc/{{ container_id }}
    --force 1
  vars:
    container_status: "{{ container_status_raw.stdout | from_json }}"
  when: managed_by_ansible_tag in container_status.tags | default('', true) | split(',')
  changed_when: true
