# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-3.7.3/charts/library/common/values.schema.json
---
strategy: RollingUpdate

controllers:
  overseerr:
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      app:
        image:
          repository: ghcr.io/seerr-team/seerr
          tag: v3.1.1@sha256:d535391db3b5a22ce02241e6d7a50ca714e75d927e46aa20456b77fa051cbf52
        env:
          PORT: &port 5055
          TZ: Asia/Jerusalem
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/status
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    controller: overseerr
    ports:
      http:
        port: *port

route:
  app:
    enabled: true
    kind: HTTPRoute
    hostnames:
      - requests-plex.peterson.com.ar
    parentRefs:
      - kind: Gateway
        name: public-gateway
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - name: overseerr
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  config:
    storageClass: zfs-generic-iscsi-csi-xfs
    accessMode: ReadWriteOnce
    size: 500Mi
    globalMounts:
      - path: /app/config
  cache:
    storageClass: zfs-generic-iscsi-csi-xfs
    accessMode: ReadWriteOnce
    size: 500Mi
    labels:
      velero.io/exclude-from-backup: "true"
    globalMounts:
      - path: /app/config/cache
  config-logs:
    type: emptyDir
    globalMounts:
      - path: /app/config/logs
  temp:
    type: emptyDir
    globalMounts:
      - path: /tmp
