kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: tqm-secret
    namespace: media
stringData:
    config.yaml: ENC[AES256_GCM,data:Kc8pze2jePMGXi8BmfQFRHLDlzfXDaME1C83o+yQAaC3apP6V2ZVkSwUqtXhG/B2WJvCoc7UrfDmGh11bdc6JB88tanFR8u8FVkmzA6hosv+bqWvMSzdjXUiRWLdLSzJni/HL+8jfrGZbkqjR1jkjsqGqg2xtnGD3Kl21U7wxbIyZu4qW02yd6uL70QPN4ToIQZrUCb4YYeKSs2s/gZOAq2mZZWtmQ45MKqmfmEiT0LzPJ4Xq+XTIjj6kfKY8WjqairclO6ANNInRyyUc5s0D2a+qiHdG9BNV0Rv84SjfTj25S3wzDvU2We1OuzlM1tNwV/xJ/Z+e9jb3H39ZoYderPuhjihimWP/yIxHzJnCq0M6pz6CfTSdSZ5AZ1fmK8ImX/9GtukIDOCDr+WZUv4xEZXvlXwuuJVbfLzGpa4oQZl1GFc+qTGPMiZ/SCci/Kgj0shriEgNH4W1cPneDHEitQVBtYXLAhfXEVj6Bx2e91cBUJ4R7ko3fNiieOxbBzyJmNxdMGPMsuJbjHu9TsOssJzKayleKzZAb/fZoowS/vlcY3UtBoKrrSudvtHC9uYFmhlDE4xxCuHdF4zFOXRjrHFAXmZxf89LIkc5pqjerYZfAnVzyhqg6JfI7CFifW/1SzcJWdEEFe+PQJ+XgCNvf7Wx6bIL4B1tCZeqjRhgAYkdmgj++aHenz9HRGocskS9trCRwnDnOy/B/3gd4fd/2u/GB2F99C6RRkFAm/dWLsTyfmUQVdzd7zEr9gKqfqhx/UMUE5fVs9U73IfwNvpkLLTT3mjYPg5r/E844GtS9za2gEHRddwfbF6ImqeNGMQfAE0AtMjx4CBmZIxqlWAA7mF35qcx8eP0dXXt5DHVsxPJTCx3MsrWan1rJZsyHAay2P1E/n1VL/AREoMuN7ZGKgrpP3u/gukroogY89KfXZMTDOU/gfHEIdkKpcyqHJ7Sk8GFf4sRZN9PL7UJvi1wv7XHVXwydp4P+imvFEI6WXcvdwqLjOyjkqhHx7IujeIN+BM6TJDPD1NNst0o4rxPiONSFA297h1XZp9Z2ucE5wh/qkxhGI7xTxyLICCIQeQma32aeCERsmm3xpcsGQemCNWPspHwgooem7PyV8cWcVSvd5v7J2SATFPABqALFTb7hOGYt8Njs5/ZFbELMhLlBc6wVaMIm/Ta6qjE3GIS8g=,iv:d4EW9X9FHXPeHyj72GrpBy1CEHZL8yLjnf3h2RcTcl0=,tag:3LtJuNAjRlyPtGUO+MvFGQ==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFakpVUWIvQ1M1RndPMkdH
            L3ZXRmpuckFSWk1EeE0xeDljbGlzRjYwamtZCnk1TDFscWx6ano1YXpscVUwU05k
            TVRPUHo4RXE0a1RpbnpKVUxKcTBkRlUKLS0tIDEyQTlPTWlvbWpMT2ROQnIvbXBE
            TWMyZjdpcm5kR1BtYmZWVGhKVlp5L3cKZkMXZw5E5SlOmI3fRv7WgW+cXarVZ33L
            w/A3kht3qyX3fI55/0NbcdEQ/rC2zLufKpVyNbK5obHVf80yOqpNBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:48:22Z"
    mac: ENC[AES256_GCM,data:sZHjpbPJi1TY2PWm337IsBJ7flg97bSdhFy0jpCaulSuuNSpynQvZbIomYvOgLnVdDVr5w+n1vWblkrqeBEqrxe1BKUpBdHs5S3CQSPive0l4d8UDv/wdlyEiEQYh+vLdYRB3XTM+adbuesaMkp4FAnEzCQd8OeR4TxkwuQPGOY=,iv:BWh1sIFNzk/KBD56NciDuD4z41kEmRxmB2r4GAPYpZI=,tag:46lVIoamy99esDPlBNVygQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.11.0
