kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: tqm-secret
    namespace: media
stringData:
    config.yaml: ENC[AES256_GCM,data:jUuWmctPfSRGA5ak1iSsmcLTVij96O9FCnrWJ+a8VBXwK06n2uWpfsLkD67ZJ6uK21lkP4h0y1mX8EwNs7Tvb8S9KOegygYFgOAo94dq8YSHwdcr73DQYZ5TomT2fye9CMNCoI49rJgfvHP83Xt8LqqQlP/OxbcwcG6AAw9fQS3yQVxk49Et/+KQ3KmxvTDKX9sRg/eOmefi6jnCMpxNfQvVfOzP4Lrwu3dZveHmV6a93h0svoUAYHL8+xbLN4FsGgqV4tZrejIREs7o3nP6Bh4eiN6F3bLdQoFwPA/KHJQ+AZ+4G43DWMMJulf1hzFYtH48/86k+ly0thI71rPqHFiwvsNTgQfdcxDykzQsQLB0r2KrZ3VgdVen978ItMLJgBq6X7IUJ1zjdiAZAKDM8ha9Dj+mvUjS8KEoD2BIExopjd+M8gsinYQDFJ0YEjrFrYRWNu5CjUDcn1NLZpn9ptxChLpwZQf203bKxy4jCR/Sh3wYXq1DY4gluFhNfoFEDFfi9bUH0X/yT1gelOZpP8BtiNiADuK9uubkErXUQKgj2tqS5C7I1soxN7zyYECg6+aijRQlvABrtDjFxj5xVxJaLuJ6WiO1LKSAt5m1IEPaBIDNa5TTm5laWkBfaatLLTRZ3AMTsSltEKQ9ccCv4ggjAhK3l/MVKxUoTCfol6RH9r+5G4bex2szs8b9glT+XviYpALhipt5+rVlBbtvZKRW2Jhc7bUpVZJJStG0neIh2sordGTKHwuSf2KVTRyQIUfzSsr0Xwg69Veks+9oNt2qpREOTSEWdmLksAsDQnPkBw3AShcSiEccpYtb4ZwQaefXcGaMPAVE5ZbJyLdFT58wIsBWfzY8+TdFSmTEYBGzqbC1+MRk+T+UBa+WhVbODJcULgWE7sSuOzOYNhs5vfxPD07q6SN8XUx/NYCy+jq15KH+tdB+XspICii1KNEIKRZ7CM8QIQM6kKfMtnKzQ1HwTDu4QvJrNWoUMGtboE1xTPT+zijQ+MAwfIL9rmFLGYgdJoxgfbkY9ZQMKQOY5VTg7F+5PNBEhjPdWVgNLm970ny77vui9PLm4cJ/kGVt6psJ53X8tSqIsFza0NSjTa7++PhAuaQUgpzQ/fOEojhU0X/TIIpNL7pZzqEJSIHTZEwMfZeFCtAzj9FjMUwgiX0nXP8DOpVmKlG0s0slqo8=,iv:A/9OGoWEU28TkAdTfrBT0LUh3nyI3BWvN2UwIAYerFI=,tag:8HysbvYcf8xSaLWiebnXUg==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VnJRYlpPdEVZanU5TGRp
            Z05JR0NhQ051L1BHYU9sQ0lIaUNONytneFFzCkRRV3B5S3dZNkYwSkxHVExNSjVQ
            TVVxNkZHbHJScTVMc1JZLzJJYVN1OFUKLS0tIHpYNVZUdGJGMzFzbXJMVzVFdzNq
            dU9sMi9NYUpZYWNiQWIvWHY3OWIwS0EKi4zcd1RHCKhAriYmwA3qkOQmxsS3GrEL
            4MmclbH+RzM6xy4H5r1MPKR0EyDVmUNMdpGODY8JzvAm0T5nQqYrIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:07:38Z"
    mac: ENC[AES256_GCM,data:LVHbzE6heHDCccIXggfiDNDleYQe8ZWaz/5873uSe2taxV1eaxW81/bDCrfsW/h/Bgy2kt5mBx46gTRh9mjvqiyM1v4Pwip4GMbcxanQSByfcNcZJds/hvVhhB0Izckb2fTFYFU3R4ESK9toejauwgF62O8J/WbuEcqX63QpOEY=,iv:uz2+a46ZxEaK9M6ZNBADC3CuVcuNbrVwdgYDt/fK0ew=,tag:IxgSjsijQXF5oUy+lUTcNg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
