kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: tqm-secret
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    config.yaml: ENC[AES256_GCM,data:AipGZaQd89BoA5A+AfL4STlM/8nq24n7hoUfHhsrKYYw0p2e5p0uVLxlCpQckR25akUH4xicXD8jgz2TxsVWQMvxnH6ElJySIoXTuC16xykg97CmpDUH3msHHS0GTGizrCfyHvRBjOQG2vpq0ELncKI3ZIdr/deyDr92w32GoXwv+RIbD6fF36d0yo8BZdAF2KfSRMSZjoMDfjOmorKRC334jJUXAir9lslFB+3FGXuK3WE9Uqo3inRtVWRDZW8OvJxXty4dRDTIrQR3pkf2FR0TUEJSvouYUy/W6XUy65sxfh/fKGktO4qrmBM/kIApjmCfBBA4/DGlW/P4X6bUwGZ+kxRINS0QOr+k2+l1VpmEC/OEyTdjH8f8jH9IH6rJdIsAANoJPlEqXf2wkiRLiULYfz/kQIMasBbWVL2u+fEGfC1v44z4k4VqNPQBxzU3H7ybAaWoZ2LSepdpJZDGjpy7IEDrsb0v3jzBkHKp/KiCtUietf+M0MsCMWocaF8BrAd+lYOisGY0Km39aZX8kTgOHzjTB3ezzqqEOD12l9Ydo6qqfRH/60ognKvBQmIkLUSXL+du/RnQjHC11lQB3wjKJg5PJa6DnZW62Y9o+V90tt/MOVELMfBmcH5VyA97+0TUevPNt9a9XkccNk6/gxvHXLpvEoYzArcK/++e8MV1ubu7By8LX3kzhOvx/WYgzc6I4GtjbrrRWmoOXh0YrrtA78N1/DFLvn2Sd0mq+RHPRoY/EojHSTXgyalKDZxiK+yTEkunt9ViKCgGuS0KsTk1EcozpQb3LSYRL0NXxHwSYKIi/XKJS6kiJq/9ulFHfVAaUnQTvUssAbatD6Owyjc80PzaiUqadZNXibzrUbuPLaFs7Rt5n72iiHd53sESQ8GdSA1P2PLIQeGVwcfn5ISfkGm/zKkClMDh2JfU+hwCRZhoxBGYOYUTd7Yqt6bnqnUmhLv0U/395NTv5WRljlTiOdDWUwkAbwj6/pEMBw1eTMakB4Pa7zzBjJwNmV1vO4nfikLgNLwyk/5KHI0KLNilEaOmMo/pSREuXvEW2TJyy5Jub+LmPK9B7TI3fCm79/iUJih9O9cVPIK5+RW/Od+/BD/g44o8qikGcQOgW3qB4mxx4K598GlvVvTAFd2MUudE6i/5ibpaODQCR8OHQUlRnpkz9xSBW5QScv+jEW8=,iv:JY5mGhG52vxDzz3BMbLA45W7UyVc0Iye047fnEbgE6E=,tag:ri9r7lSgjHDA6EzTPvcwBA==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT3lYSzZUM0xWNnJodDgw
            NjhLbm5FT2ZsYzBDTnhYVDN3cENXdlhydUVRCm9LMzZ2NzlLOEFSbTcyWHQ3MW5K
            cmxxbm55ZFdVRW1rMUJxQXFKYTN0QW8KLS0tIDhDdXh6TkhEVkUvbmpycTU0UkhD
            NTY2cXZ4aWxCN3E2RGovN1VKWWlFeHcKjxD6WUMxGlCZQyJLsGuFas4RqQPCge5W
            jL0CS2kOwJ+4EcVYDWOe15oOznVU8IsB8K1h9YNyBtOB2Uv1EECaiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:13Z"
    mac: ENC[AES256_GCM,data:nl5h4mOcIEOf0kVpoJrTpVkrEp8luxzaiQrUiIDCF2eBA41JVpidIYu7yVZ2jQc4tCuylxNvxU9vy+lxONDf0KMvGknV14yeF2hAM1c1FBx2Jk6MTVUISBuRQqJxPNkR+KJRjX4VqJgpTTdxDkKIJHYCnvfnhxDKyuNpnvUhdYw=,iv:px4el8S9x1A1+gw4BUvy3ZWzXFJBEN3XDx3yl1c7jvE=,tag:+DaKMb/2LLiGhsAuWfNFNg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
