---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-3.7.3/charts/library/common/values.schema.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app qbtools
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.2.0
    helm:
      valuesObject:
        defaultPodOptions:
          securityContext:
            runAsUser: 65534
            runAsGroup: 100
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"

        controllers:
          prune:
            type: cronjob

            cronjob: &cronJobSpec
              schedule: "@hourly"
              backoffLimit: 0
              concurrencyPolicy: Forbid
              failedJobsHistory: 3
              successfulJobsHistory: 3

            pod:
              restartPolicy: Never

            initContainers:
              tagging: &container
                image:
                  repository: ghcr.io/buroa/qbtools
                  tag: v0.21.1@sha256:fd13085f7534719b7b30828684661b7f5611bbc4156831123775cfcd9b8f2eb5
                args:
                  - tagging
                  - --added-on
                  - --expired
                  - --last-activity
                  - --sites
                  - --unregistered
                  - --server
                  - &qbittorrent_host qbittorrent.media.svc.cluster.local
                  - --port
                  - &qbittorrent_port "80"
                  - --config
                  - /config/config.yaml
                resources:
                  requests:
                    memory: 128Mi
                    cpu: 25m
                  limits:
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL

            containers:
              expired:
                <<: *container
                args:
                  - prune
                  - --exclude-category
                  - manual
                  - --exclude-category
                  - cross-seed
                  - --exclude-tag
                  - added:24h
                  - --include-tag
                  - expired
                  - --server
                  - *qbittorrent_host
                  - --port
                  - *qbittorrent_port

              unregistered:
                <<: *container
                args:
                  - prune
                  - --exclude-category
                  - manual
                  - --exclude-category
                  - cross-seed
                  - --exclude-tag
                  - added:24h
                  - --include-tag
                  - unregistered
                  - --server
                  - *qbittorrent_host
                  - --port
                  - *qbittorrent_port

          orphaned:
            type: cronjob
            cronjob:
              <<: *cronJobSpec
              schedule: "@daily"
            pod:
              restartPolicy: Never
            containers:
              app:
                <<: *container
                args:
                  - orphaned
                  - --exclude-pattern
                  - "*/manual/*"
                  - --exclude-pattern
                  - "*/torrents-files"
                  - --exclude-pattern
                  - "*/cross-seed/*"
                  - --server
                  - *qbittorrent_host
                  - --port
                  - *qbittorrent_port

          reannounce:
            containers:
              app:
                <<: *container
                args:
                  - reannounce
                  - --process-seeding
                  - --server
                  - *qbittorrent_host
                  - --port
                  - *qbittorrent_port

        persistence:
          config-file:
            type: secret
            name: qbtools-secret
            globalMounts:
              - path: /config/config.yaml
                subPath: config.yaml
                readOnly: true
          downloads:
            type: nfs
            server: nas.lan.peterson.com.ar
            path: /nibbler/media/library/
            globalMounts:
              - path: /data/downloads/torrents
                subPath: downloads/torrents