---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-3.7.3/charts/library/common/values.schema.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app tqm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.6.2
    helm:
      valuesObject:
        defaultPodOptions:
          securityContext:
            runAsUser: 65534
            runAsGroup: 100
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"

        controllers:
          tqm:
            type: cronjob

            cronjob: &cronJobSpec
              schedule: "@hourly"
              backoffLimit: 0
              concurrencyPolicy: Forbid
              failedJobsHistory: 3
              successfulJobsHistory: 3

            pod:
              restartPolicy: Never

            initContainers:
              retag: &container
                image:
                  repository: ghcr.io/home-operations/tqm
                  tag: 1.19.0
                args:
                  - retag
                  - qb
                resources:
                  requests:
                    memory: 128Mi
                    cpu: 25m
                  limits:
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - ALL

            containers:
              clean:
                <<: *container
                args:
                  - clean
                  - qb

          orphaned:
            type: cronjob
            cronjob:
              <<: *cronJobSpec
              schedule: "@daily"
            pod:
              restartPolicy: Never
            containers:
              app:
                <<: *container
                args:
                  - orphan
                  - qb

        persistence:
          config:
            type: emptyDir
            globalMounts:
              - path: /.config/tqm
          config-file:
            type: secret
            name: tqm-secret
            globalMounts:
              - path: /.config/tqm/config.yaml
                subPath: config.yaml
                readOnly: true
          downloads:
            type: nfs
            server: nas.lan.peterson.com.ar
            path: /nibbler/media/library/
            globalMounts:
              - path: /data/downloads/torrents
                subPath: downloads/torrents
