---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app stirling-pdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: selfhosted

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@4.6.2
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/stirling-tools/s-pdf
      value: ghcr.io/stirling-tools/s-pdf:2.9.0-fat@sha256:82f88f27b700c7d3b79540d67e08fe79d5d4a9c6df7de6130593ecf6b600bca9

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/stirling-pdf/
    targetRevision: main
