---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app stirling-pdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: selfhosted

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@4.6.2
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/stirling-tools/s-pdf
      value: ghcr.io/stirling-tools/s-pdf:2.9.1-fat@sha256:a568980579d6e9dc89d308e16e58c510298562d69e04eb562b291b0f99c5cc2b

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/stirling-pdf/
    targetRevision: main
