kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: stirling-pdf-secret
    namespace: selfhosted
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    SECURITY_INITIALLOGIN_USERNAME: ENC[AES256_GCM,data:E1n4xoFgmb9Y,iv:0D87G/AE7s5exqsWW6xHnvpxx6SP4hgd6VLGL/0Caqo=,tag:Z60Hc0+17Px800Pausi1Dg==,type:str]
    SECURITY_INITIALLOGIN_PASSWORD: ENC[AES256_GCM,data:I2itXTJmU0EzMifnyMrhwK/R5UqKqUcFsA==,iv:Y7FaOYOboJTW/vdMo1VdHYsEjToz+YfYmMwKXE7aNik=,tag:r4hJnfgHvp67EwNDDES61g==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaazBRalJUVHhXUk5vL0ht
            V3pUUDlheEdJWmtrdFYvUE1heWpaOXdHN0RnCk8vei9GZHhMTWdKeHRFajJBWEMr
            MG8wMG1JbHpaZWd0NGtmYTdvSmsyak0KLS0tIEJzTUExdGhUWlVWTlE4SVl3THl6
            ZEJRZ0pMTWdCUHlwVVJyRzVlVjhRZGsKsnyZwnv6rptCVTfgzgeDw3PjYJN/TWtG
            fieXmAN5l5mC2Ut+488QvQOqd0m7j0oL66y2h7nHh+9h+ia2ZxYp8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:13Z"
    mac: ENC[AES256_GCM,data:ZGx+Ows+SMZijlRLHGgfeooIMjsOeNM0YEg70FKI/3b4KTe+tafRXAajRoK5WABiJiQX7zldOWarJbH4WFg8Ems7b16cWvqK638gjPGY4myB2jA6T0z5WGVf0QJuklL4d+7o71gPngvr9PhDh++NVsZnmCItuUoO6oy1Tno2SPo=,iv:ws6HqNVAkmfwaGu0E4n24oN5W25vS7Qt24ug+CiQEIw=,tag:4pSXh3+cH3Ru7scB7NSNrQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
