kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: stirling-pdf-secret
    namespace: selfhosted
stringData:
    SECURITY_INITIALLOGIN_USERNAME: ENC[AES256_GCM,data:Fit1NQ6xjS9u,iv:t7/1KmRSt641KtycXIXgtgXTsv83mvRaCf49OgBRX8E=,tag:wundRGu/IYkUoF7bTXI1Ew==,type:str]
    SECURITY_INITIALLOGIN_PASSWORD: ENC[AES256_GCM,data:77ll6sY9t7rXNILoxBdwxY0X8I8t/z9oNg==,iv:qS5bE8KHY4Dban7FXita5HRSMr1Lwe7VdfqPuC7gfi4=,tag:or2jTdmoHixyQTe6lP/Grw==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUU84d2RJYmIrSVNCZ3lo
            b2pHRVBhcUNKcURwTWpmRnVFejZ1TElFb1gwCk5nU2pGa2hJNkJPWWk0QVhzVEV1
            L1ZlVllVOTJGUGRwazZWNjRQR1J2a3MKLS0tIHV3UFV5bElUUjI3T1ByQkVMWm1k
            YzZQV0JaOXU0Y0FtNUNuLzdWYmhqeTQKnR33k3DwwCVSePETk0pKF4ZtQalHpmR3
            4cxUmHE9wUDJK7CqWNa1lAQjrTIZcmniq4zPTt25mem9u0zNkn6IJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T09:32:10Z"
    mac: ENC[AES256_GCM,data:GUN65Q+gKsw/0Jewr5j7MrUjVUiHy51Vy36Wyv2dFCKG6CZYP+hNCY8p+J5ASqvFclUYwaA1wFnKipCo38/WjOIdD7YMjnOf2g8d40g4TvOe1eU14ejMQNj/xAnm9zK1l+v98mnMGIs+NNERRDYAfnebruORtX/fToW9m2eahBU=,iv:IEx37hozKIHEfq0rIRqh4wJ53HTYOmL7aYve/N4WCus=,tag:TudFjztmgvgld9mqO4a/Bg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.12.1
