---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app recyclarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@4.6.2
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/recyclarr/recyclarr
      value: ghcr.io/recyclarr/recyclarr:8.6.0@sha256:3c38ceeb54438dd8327e4e65c9b48ba601a6d20fff833342d93c9b0bc4b1930b

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/recyclarr/
    targetRevision: main
