kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    secrets.yml: ENC[AES256_GCM,data:ASPrn7Po4jXD1cYGrtrEJc9ENCq1GPyaMP2Nk5SAu+V4fOlJNxHEdJNHg23NAQQ0PS5Lj+DTAF9yz7lcJ1KCRZJ/NSBouq+Gxd7yBCyQRJ+q0giFZY5SN4ztfb2Yok95IyyQb3Tgn5Z7wDiba90Au4l2G4rnmQEBl1CL8kauho8U3r6ULWHaFNWD1jtCb2jZZ8+YPAhYMRMQQ/wlk+XODOfK/U5yBRUh/KJXSeDntOMlFer7/LRMqcEMvdKTeLJEUFc7DhDsJVhiJscNKUXOUaQ=,iv:mC0ehZHu9AQYEQhy7jblu9dd26ABjmk8E8CZUMAfWwU=,tag:0wbavLMw5UjARwdfuSD9pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFakpVUWIvQ1M1RndPMkdH
            L3ZXRmpuckFSWk1EeE0xeDljbGlzRjYwamtZCnk1TDFscWx6ano1YXpscVUwU05k
            TVRPUHo4RXE0a1RpbnpKVUxKcTBkRlUKLS0tIDEyQTlPTWlvbWpMT2ROQnIvbXBE
            TWMyZjdpcm5kR1BtYmZWVGhKVlp5L3cKZkMXZw5E5SlOmI3fRv7WgW+cXarVZ33L
            w/A3kht3qyX3fI55/0NbcdEQ/rC2zLufKpVyNbK5obHVf80yOqpNBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-02T16:14:00Z"
    mac: ENC[AES256_GCM,data:0oZCJEZBASFfYcEFRXOq/kCU1S9Lc2woTRseN66RC9XlVnD0l6G0tB/ZzKyvfjtBQKTSkUDU9GoeE4Xjf82RBi+Rs7AoyxSfquLij+rbfn8VBNHlVfLQMo52VfYQ2NowfiKKW5qBszgWHmgFt5tJYk+ij6njQmcYU3Y46Y+Tqi4=,iv:c1LzJ6nb09/68nhFXyEfmS46X7nwaEwnVGIiSMwBid0=,tag:ygaoPo1JFNT0+scY+u8/dQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.9.4
