kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    secrets.yml: ENC[AES256_GCM,data:vRucUf0WQ2Ya8MRkcUlKE98I5GOBjaCRDLFDAitnGQJQ6QO2sSHZ5UWW1MrxZUioW1Ru04jDfiFyEJYdIVKCbpdaRxZ01CHOUF+Ydxw+/vzsAbIMAwMmZAZyDGzTi49BSJpCVe2h1V7W5m7Csqb5YWvDnr1aH8SN2cr/4wCs12jPLBBxNFVYDmm9vbDpa8tX8j+RlYpftrr7XrEuD02CNR2Gz+HYMU9yTNYw25BxvkjFapFeaBfzXg/SV1HXvrFZslj5tfjqWYiiX8eIKdwfG0c=,iv:1a6/MxF89PwiZfy85vkJhlA9nZ+aECh+6qRZRtiw43U=,tag:1UIcEINlcrKbs8d1+ejAJw==,type:str]
    sonarr_url: ENC[AES256_GCM,data:hkQSj0R7VGQotmUZ1si9z5O47aem0YT+oZYXxEDzk3F1Nq72lMqhouWJ,iv:7qzDISBY1Ony0KZWobpRVKnq9zXVIWQdSWFTUcReKwQ=,tag:cj0iM6bsGdqhVqqSJzn8GQ==,type:str]
    sonarr_apikey: ENC[AES256_GCM,data:cyNivvDwFwjOV3c+QLb58yXVYio8S+oeXLg/MwLIr+s=,iv:de+uVRiG+3zVM+WLjjWz4evyqEVDzyaEdmNgDlyL6fE=,tag:J70ebjawGSyodeQM5zYs2w==,type:str]
    radarr_url: ENC[AES256_GCM,data:jFAaw9b9cyz6BcQnAzPHOEP/lNv1xsdtqcIpOMWKK/bSSrF2gVLEFEXt,iv:Eb7+yM17M2c+3gZHXx3A0Hb+pcL16KMrOp1MPNnNUYk=,tag:qP9hR/ndsGU9unJO/qFBmg==,type:str]
    radarr_apikey: ENC[AES256_GCM,data:lYifF/PSS0RYJZ7ZQafz/d5u9d+79CCuVUxBGHR89fI=,iv:LoE1vyVkD89JwDzE7Zx6i9teMBztH5P+wMwD/TKKFaE=,tag:0DJm5lUIrppzAqFXaxEA+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFakpVUWIvQ1M1RndPMkdH
            L3ZXRmpuckFSWk1EeE0xeDljbGlzRjYwamtZCnk1TDFscWx6ano1YXpscVUwU05k
            TVRPUHo4RXE0a1RpbnpKVUxKcTBkRlUKLS0tIDEyQTlPTWlvbWpMT2ROQnIvbXBE
            TWMyZjdpcm5kR1BtYmZWVGhKVlp5L3cKZkMXZw5E5SlOmI3fRv7WgW+cXarVZ33L
            w/A3kht3qyX3fI55/0NbcdEQ/rC2zLufKpVyNbK5obHVf80yOqpNBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T12:49:21Z"
    mac: ENC[AES256_GCM,data:q08GmaqiS2CWYlQRo7/19kTuyVOFc+gdaujaWZtgRxt9M8Lh1D7D8eFvMuV/ZyWrwpGNzpEf43uDjkGg8tHgTWZmNha69gGB3XkWql9/lFguT6Uv+TZTuigVvX2uMXI22RQwivIUJy9dz1t27qQvWRqsBYkzr7M+7AxRKE/kwTU=,iv:xGQ+1DnorVVCfPvolkKrUDOTRhcnkm6xAA01LiPH2ok=,tag:601b7jmrHphGkTlGRJnWYg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.9.4
