kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    secrets.yml: ENC[AES256_GCM,data:r9mgGVst2ra9xj/AqyQJBymBTjJSPzAoi2NttCQ+d2MzoWfPuHjd/Cde1LjBxCVxzUkgl86XSDAYqxYo0F+ghamTE9EnFubENJEvGXpWYigh4nOl2UP/smB+8jVId2my9wh4Zo4/J7Wd8WLvH3kdQOVksNOjgVPeu8So04C8RSYulahABaeOJ7631daL8R0Pwr9jrHRns/8uhVXPUtd0JNjOziqJXyKoIGv1iX1Y0Vn3aNMXi+1NvAhAj4tuMMN4NG3vlpvPVYh7AQycMSzPbVU=,iv:i4ot5qTjs+GFj22uXRR+E7jMOthoUow4hQB3tveTO68=,tag:d6g6Q+DbNa5LOO6i6c3Xcw==,type:str]
    sonarr_url: ENC[AES256_GCM,data:76xOBvrDo0kJNQCm3upLgMcS21BgL4NqDaVQzMMnYq98dd3s9WsInG4U,iv:K/NIBk+ID8dMd3VTd9zOMJteHkvvi1FKuj7qdRPuGJY=,tag:XOQM1l153wZReKkpX5XxRQ==,type:str]
    sonarr_apikey: ENC[AES256_GCM,data:UN8eRVVQSc5OPQlSSHmVTOq10MNNQO+APZbKaCL2GDI=,iv:z/7HTQke96xwcFyrHGFPyHQpp93VqRLmKxZLSziORQY=,tag:osG6WnsGVTfL2NaEf9YvlA==,type:str]
    radarr_url: ENC[AES256_GCM,data:er/jc1qloTCZ7A6GV8LbvOfpeAyNEntxrxkNwluknti5K33Ot6Fb/5IU,iv:BGCaEJq3gKNhlzbiAPZZ/YSJgy/lbSDohPPLLGDe1mQ=,tag:6A7krpJEuj6soN8/QsAPvg==,type:str]
    radarr_apikey: ENC[AES256_GCM,data:bX29Fb0rpZhiwHUF22b7iuXc7phnwOVMKwuuVgeBjvI=,iv:nuSLWVnogOTIMfvZ17RYvbTd5c+nY1dL0qARbdMJPx8=,tag:qEASDDPRjTj3bdcykKIOsw==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVDF5YkVBY2RqYXBlR0lk
            T0ZSVldzNGVUR1NUcWtYcFo1RUpoeE5TaUJzCndJeDIySEdrZnpNWXFpNVVRbEZa
            Q2lvNExtVWhib3hrYXg0MHJpejZoY2cKLS0tIDgyTGk1N05iUGdFMTJETXVGSDVm
            eWdyUFFZQkZNanNMek5mMndMeUgwMjAK0v+0B7ST/iGYBA5PxmTaYMrKuG4KI/rx
            kZEnzJfBf+g5F8+LzeXhwiJJlTJ+plGL76qGHxEazLu4wVU/REeEzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:13Z"
    mac: ENC[AES256_GCM,data:Pv6NyCd06ly6Ctu8se9Uq+J6XOdyP8hfh5Qo3oUr9gv1u/FmgTm0h8i2ZaxL1xX58fSvElAAq6XgKg63BNBZ+vFScxZKwo6DpZpXDojgaMGAWfdd7nf3pwnTZtVqQo0b1fjZRS+FXBrxHIDfeaeigL1yznMg1yTRQ8tQmCr8V5Y=,iv:ELXCp3tHStsokHvjQL1LF2hiJRpvvMWgrQPtDPX29IY=,tag:QHbKSbrPTnx21KkZjmA3TQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
