---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &ns monitoring

resources:
  - scrapeconfigs/node-exporter.yaml
  - alertmanager-config.yaml

generators:
  - secret-generator.yaml

helmCharts:
  - name: prometheus-operator-crds
    repo: https://prometheus-community.github.io/helm-charts
    # renovate: datasource=helm registryUrl=https://prometheus-community.github.io/helm-charts depName=prometheus-operator-crds
    version: 29.0.0
    releaseName: prometheus-operator-crds
    namespace: *ns
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    # renovate: datasource=helm registryUrl=https://prometheus-community.github.io/helm-charts depName=kube-prometheus-stack
    version: 86.1.0
    releaseName: kube-prometheus-stack
    namespace: *ns
    valuesFile: values.yaml
