kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:kObfE9NR486glUjajkgXUZNygnymJZhigmIY8JS5,iv:uT/DYj/EyxS7OddrdXY74hLAyqMtm3uroOUJJo9hvkU=,tag:pFiJlRMH6KgabQ26ID8rPg==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:6lIYzMiWOdALIY2vubAtNjDSdMm02SMaMtTn+alC,iv:Shl5Xw0aujgP/FmVYD4atJUVliv7dRUgT2Zl3lxW7+0=,tag:AtGG5xmTHNXb674LXmQ5kQ==,type:str]
    healthcheck_canary_url: ENC[AES256_GCM,data:QvseSENn+fxcieYUih00CeVcIN7oj4yugS82fpYdx2w/DEvYMKVBHdEizkf9QKmDcWkQ1mk08oDtAohW9BEdA7bN5++RjGMgB/pYswGi,iv:jltJyuwyDiRQ4upVaUBVpAeSzvoR+SsbITakqMSwGdk=,tag:dPoJNroOCOAqYXB5SoI4ZA==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRXozVGIrV1UxWFZiODhu
            Y2dadjNXNjBlWHJmK0pHNDhxeDV1YWRFaVJRCm1CUWlaV3lNaWJvVDZDVXlnR0dn
            K3hpTFNYaGQ4Q0xvdnBUNnhyMUlldm8KLS0tIHdHSFZwalVza3dxT2Q0VlJNMUZv
            d1QyUzBoaHU4a1JSMzNCb3NVeStYK3cKw3odILxoR2q+w59zM1SlqsDskvCJMa13
            ZyxkRbfplnK257Mbhbqhq8HUBpNnZFWUuIGKHw3y4tohI9tcNOckrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T20:00:05Z"
    mac: ENC[AES256_GCM,data:pL2uClkABNe0MuGaWMIOSzddxTlUpXbO0ol6CFn2+SGW2y5hfcMUsSx1TsL969aMlQMxYEAFoRqXouidrBL/1SL79o2QzEP3WaoFkXy2oFVSGKNzRS8iRy81eJlX/QRMmw+ha3swZALCGOI0OLRxSLe2UTKsxnI3tfir2b7NoxQ=,iv:ewIm07kLCeT50emPBUNAN9bS6Y+GcRCmsQ2D6GRjZ3c=,tag:zylkuIzfDhc2V9g9+fXZ6w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
