apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./mosquitto/acl-configmap.sops.yaml
  - ./mosquitto/secret.sops.yaml