kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: n8n-secret
    namespace: selfhosted
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:1c56iOQLjoC8AsnYPMuqVg==,iv:sqe6FDVEfXbiZxUvgTkaKlLIJ+nSs1Thy8Q/3KCVe4M=,tag:9GQm9cTrT1coo6G/gNK99g==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNi9hQnlNREV6ZUtuM3lZ
            cmZ2REluMHdPVWoyd3ZxdFRtMnJMUk1jZWd3CkppUFpvYWc0aGUxSGZhYUI0N2xT
            ajRqSjZJMzZaRWcyOGdCYm9tVmxtUjQKLS0tIE9UNGE5a3BqZ3VDVm1RRWIxYUNq
            Z1lCeXJzRk50dHV4SWVYWGVRemRVQTgKYLcmMWN/RozAYNvPNMxlvy3HEYWJpZ38
            4ViYBh97zhcg5S/oM5hUarfmjDK9j3w57tIz0Fn+LFJj0wLwmU+/Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:13Z"
    mac: ENC[AES256_GCM,data:GtpjifaG8qsnuap1AfWjI2VTRDu2/h9nEpM586FS4ZcmsQ/DiHfZzCkpDxPO5WOZJ8yqpLlZki5b9oyky54L1Shl8sOyvIRG9CkdZ0RiMybf+1Suk1ttb1skuBbjkCKd8fGWvzdlvHLH/UDaYzLm2VR3Bu3TiN1EYL88yF0d6RM=,iv:GxuN1/ryeOKPPZdAfe5zU6eW6Z5tmH+p5KeNV6U4hPY=,tag:27qZ47OLranuhK7H9oTtnQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
