---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.17.1
    helm:
      values: |
        runtimeClassName: nvidia
        gfd:
          enabled: true
        nfd:
          enabled: false
        config: 
          map:
            config: |
              version: v1
              sharing:
                timeSlicing:
                  resources:
                    - name: nvidia.com/gpu
                      replicas: 8

  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true