---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

generators:
  - secret-generator.yaml

configMapGenerator:
  - name: kometa-configmap
    files:
      - config.yml=./config/config.yml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
    version: 4.6.2
    releaseName: kometa
    namespace: media
    valuesFile: values.yaml
