kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: kometa-secret
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    KOMETA_PLEXTOKEN: ENC[AES256_GCM,data:c6/jcWBDek6qpW0Km/9A3JTqOsA=,iv:iH4lbPbly0bjgGanrRPlAUXrGV6NNx4+JxaMBpdMHiI=,tag:mxI55PHFWSbamIrvnOJ8oQ==,type:str]
    KOMETA_TAUTULLIAPIKEY: ENC[AES256_GCM,data:uY4u67M5I9mvAOfgzKQfepLGMzDUl7D2AAGNMDlFBt8=,iv:3len7rfSOC9pD2Z223EJ0J7vcwX05aYwvsGOmZwgxo4=,tag:2nJZU+WASZWd+b7YxuEaRw==,type:str]
    KOMETA_RADARRAPIKEY: ENC[AES256_GCM,data:DgYTFmE1CmoJgBW0cJhlIUxGTfVUzh+OeGAb4vC5Y7g=,iv:GTmBAQQxf63r4tD1meaaHbVWvR+y1XEDSHHwa093EjY=,tag:atWoKgtK6c0f2lK2D/gOZg==,type:str]
    KOMETA_SONARRAPIKEY: ENC[AES256_GCM,data:stVNskPuMxAbKed/7bFGNTkK1P+C/sojunqjHCfpjzk=,iv:fRnJQjlX/lWP8ibZXtx7NEZnufbQ9ZJHMiOeZGLJwqs=,tag:+zy091aOOL1Nx9evrV5zqg==,type:str]
    KOMETA_TMDBAPIKEY: ENC[AES256_GCM,data:Yn5p2lNGQIm/MTyKcW2hvNduk0Vgm4DgTlX09kQ1590=,iv:ji03jHKapa1Rlc4Z1FpxMv1vZhC86XQK4aioh7ynnes=,tag:kz2CA4Bl/2veCxQoXB+nlg==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NXlWdUVva25lc0V4RXhl
            QlhiSlZNUCtFQUZldWlVbkY3a3paUnlkNFVZCklKMVVrSTRIaThxVWdNRW1KSVpH
            S1QvTmNxK0pFNFIyRG5KK3NJWnJ3Mm8KLS0tIDBySHpPUjhFNHE5OVdIZWMxSHFP
            ZnNaaTdpODhBUTEwbVhMd1F6UnE3WWMKMeaW40bvSTEgFOmT1uejrfMKs9Iddm7v
            w8hT0JuU6pAeF/dd9ukqLvRYEbM28aXoBwxK0JKx8KP1ou6Sbe8kvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T12:50:13Z"
    mac: ENC[AES256_GCM,data:O8qAZzhT4ax6m2imZWrtLs9r2t7LksZ6XO4H8sxQ2hkAU/Rq65ENtfsddlS72umA+fFWA8bKQqMfuB3mAJEpG+EUptngNhmqXzcmOSuZfPkfUK7ud2YUMSbGW2ffOImH39TYpSM/WOWuWNqy17pjQRE756zcoGKns26ferWqgo8=,iv:wYu5a/g/wSf8bFX4jMBcBbrbiHsYAeYHhA1n+zITcqU=,tag:aG3aNj3njGq5yIQoaoODeg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
