# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-3.7.3/charts/library/common/values.schema.json
---
strategy: RollingUpdate

controllers:
  kometa:
    type: cronjob

    cronjob:
      schedule: "@daily"
      backoffLimit: 0
      timeZone: &tz Asia/Jerusalem
      concurrencyPolicy: Forbid
      failedJobsHistory: 3
      successfulJobsHistory: 3

    pod:
      securityContext:
        runAsUser: 65534
        runAsGroup: 100
        runAsNonRoot: true
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    containers:
      app:
        image:
          repository: kometateam/kometa
          tag: v2.5.1@sha256:20388de48f0e088ad9feb9904f6a452fd9ef933a79c7b2bf186e388224e8f437
        command:
          - /bin/sh
          - -c
        args:
          - |
            mkdir /config/assets 2>/dev/null || true;
            python3 kometa.py --run --read-only-config
        env:
          TZ: *tz
        envFrom:
          - secretRef:
              name: kometa-secret
        resources:
          requests:
            cpu: 10m
            memory: 1Gi
          limits:
            memory: 3Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: ["ALL"]}

persistence:
  config:
    storageClass: zfs-generic-iscsi-csi-xfs
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /config
  config-file:
    type: configMap
    name: kometa-configmap
    globalMounts:
      - path: /config/config.yml
        subPath: config.yml
        readOnly: true
  logs:
    type: emptyDir
    globalMounts:
      - path: /config/logs
