---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app rotki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: selfhosted

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@5.2.1
    - name: Image
      # renovate: datasource=docker depName=rotki/rotki
      value: rotki/rotki:v1.44.1@sha256:1b6defb5aef37cee38ca6746c594b2b843a4e909cd977234e7aee0c00b6266c5

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/rotki/
    targetRevision: main
