---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app plex-auto-languages
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: media

  info:
    - name: Chart
      # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
      value: app-template@4.6.2
    - name: Image
      # renovate: datasource=docker depName=ghcr.io/journeydocker/plex-auto-languages
      value: ghcr.io/journeydocker/plex-auto-languages:1.5.2@sha256:43c7a77e1530cc87d78b7aa0e8ca66fb15b18caa97fe0e21f210137da267b192

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true

  source:
    repoURL: https://github.com/mpeterson/homelab
    path: kubernetes/apps/plex-auto-languages/
    targetRevision: main
