kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: plex-auto-languages-secret
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:ciKCBz+Bk2YeeMp1iGzAAxmVpfs=,iv:7vOgIVXxWmU6oR5QnMphNifBLR6dhG1mQtT3SjPpgck=,tag:Pf+3Txv3pBFicAwGOZ0rWA==,type:str]
    NOTIFICATIONS_APPRISE_CONFIGS: ENC[AES256_GCM,data:B2f5iA8EPDLj+eCQocOG5K2Sxcziv+cMJSozHXiRLxX29Ioysfu7u8OuGswGlrsQ7dAsL0XXzYK605gHvw5Ase12xhsQs9g=,iv:I0ngjppQNceilcUpIJAg0euQDDK8g3ZGKJaAEh8A1Us=,tag:tcP10hTjzhwARmTz+hQxyg==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS1c5RVdWSnFIblVzdW9V
            WVREK3lvWURRSjdzOW40TW4xZENFZEcyYlFBCng0d0RzRUR6YkVBY1QvT01lQlhM
            Rm15MXpjQW5oaWgyRlE0eHVBYVp1MFUKLS0tIDR1OGZVMU1wdHlCZXp0SFNrdlEr
            bTNaRXJ5QWNKcVpPMVFZd2xLY04weGMK4pS8TAk6ZkqIJ2tS3h1InYS5dw7E5rGP
            jd9wxTKEgpsXO0WSNvSdw4M4WEWYWrTZMxllVzEz/x94WCQBx3BgHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:13Z"
    mac: ENC[AES256_GCM,data:VuPqaRsWb5qi35uzyusVPQc7u/SGEh8JSYbqZOmWLk7WpF+Ios5bfv5Vi4D58FSRSoti++IaNIHeYqIYP0E+3jptCGld38/7eHlIrtCF5pCs+LymRnKiowshRcekb8tWyjYMHJh6JS8SyiS5VetAfjejrDnSsoCMXcvEDkSDVWY=,iv:B0Y4Im2ycw/w19YnwF/dWXG4JVO6fDg0gC1xqK1AiL4=,tag:32nB6BfDB2i/zBMGTEVmvA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
