apiVersion: v1
kind: ConfigMap
metadata:
    name: acl-configmap
    namespace: smarthome
data:
    acl: ENC[AES256_GCM,data:2TO/1mEXsMCuGQEhdMkRJuMQjaj9rgu+XFj92GSdajdszvEK4PTzSch8ujvr/hkoFcx4dpA2jaAs3DuQR8ZR+TYrWfULiGj4cPk8yqa/gRWiLZX2F9h9MIvASY3FZugjOQLMKVQmOZCwmg871A6lF8J6ChdOx+35WexJVtvf7cshCFsgEccjoVRxvOg/8jsNHfvbY5zA+BrkTAHUhL2zd5B1MTACqp9xhKaUw/PKl/jCtXxmrMcnQ3f4v/k6En+1HxNeX0a1LYGD55fQer0JWD5wS5SYTqdFKinDE1xbDbaRNtTzWAkCUiZdPtB5+DUZPPZ58DUoLg==,iv:zuye2px6XF0voWJGheKXgC0m9a4kICgZaVBiv7FWzII=,tag:rwwdet0im7tAnNUZxtMyEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbzluZmE2WmRpU1B0UG5i
            L2l0eUFVcUNVdGRMNFVWbUZMMm0ydG14WWpBCkx6TlFvdnJmOXlBT0UvdnhxaU9o
            Y095emJMckYxdHBTOG56d2ZBcy9PUTgKLS0tIFFZaGs4ajVLZWEyOHZpV1Z3eWd6
            cU1PcUxpUTduZU9jM09JZmswdzNoR0kKlViiRbXzqq8OoH74MwKd3xBaRV0+l300
            7stdasNbsxpQKd00xINFwHCt2jAjjBZYf9WrdOClCIpjSwP5M6eWTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T13:28:36Z"
    mac: ENC[AES256_GCM,data:kDNxnRTd1RRISaFKLWudqJNBsSSur4w4u+3ZZkxR80IvKS9E/NoUZ+z1+VMkcBPMP2iVfnh3gwJhc9EQAzPEduAhRs3te4FuYLi5d2+LftiZncAF7fHHzelXHyaaZluuhgMcX2+r5foHaA/4dtbD/apvfovYTYttne2FiA/o03E=,iv:7nR4MWiMxW3Kfpj6AQN5H120uk+w5ivy4NwnzOvkO30=,tag:q6GuOrENKANsuPkxBNdSXw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision)$
    version: 3.9.4
