---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &ns smarthome

generators:
  - secret-generator.yaml

configMapGenerator:
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./config/mosquitto.conf


helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    # renovate: datasource=helm registryUrl=https://bjw-s-labs.github.io/helm-charts depName=app-template
    version: 4.6.2
    releaseName: mosquitto
    namespace: *ns
    valuesFile: values.yaml
