apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-acl
    namespace: smarthome
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
data:
    acl: ENC[AES256_GCM,data:2SzF++3hM/IT5y64kdfRushNSl7eu547h0rysQPdmdQehy9PAtbSvvnbyt4Qw9BOo44TUaHI0UQmNSPd95V7+qOpGFJ8oIhSVeWB2UIFnQzJRrRj0/NA2zVLqElpoxLBVqn6ZL6jWetIFC+qG+O6eANrFTJyb2zAOwoW28zX2CMrIZshpxS4peJU1+ooYwBD1xDmrEQTd9Rut9/thGQVqnIYBdgXBkjOju9cTLwFevjhCUlgm+G2E0k/6D3qZVEM/Khr/iyCEvW0mVJQW/Do7m+1dD+kA9/LpQPIAFjTSII8WWT7rvLgahGiZM/lka/R2Gp5oHKz0vtn1hUSOYWllhGKS7ivFoI6vL+zmL2GpTwvFKb5jPQHI5j0U38OKg==,iv:HUIIZk87oJod/6XxwP/g9M/qPzjXlslx+gbKrypqz48=,tag:/JYkhTmrB6fngcrAVduj/Q==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRHhmUmdlNTVKWXRnZ082
            bjk2c3ptZWNBcWdsKzVTZGczaXlpNjdia1ZFClkwblpETmxkQVhrWFBOTnloZmlz
            RmVwVkNrcHpoWStFeXVRQjI1cXVWWEkKLS0tICtSSHgrbGpsVHB6M3RIdWhVdXNx
            K0d3WWZ4VFNxdnRJVXdZbUx3dG1nWFEKVV+XnmRb+pgp+ifOUubXRL60BvACnfXV
            EaFayelqk2ry2A/oEF3IFw4A8BXzTkdckKE4IMDD/9aWwb/qVRag3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:12Z"
    mac: ENC[AES256_GCM,data:/QwtKAvN8KobpXA7LfX3k+9AfGCAtnzNIM/fdCDBhUeV+QB61VtwDuMqFK0zcJI5yHPE9Ku4Y/Y0XRUQyIKk3KLB8p2dMdFKPsR/Vbyk2qYWqQH1Cu/YaXuGjVKGUVVa2jTDMSXmG9MqEYrZ9wDQkxHPqL1dIKeNPsQ4ojJ9Z2w=,iv:CDJcn9wtGD2uWOXnwK38UvBVY6tL3+M/OWOZgUQrpbc=,tag:jw5ftWjb7wj1cycMvJjwkA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
