kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-secret
    namespace: smarthome
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    passwd: ENC[AES256_GCM,data:Pu8MgNDI5ysH4wmIDJSKwI49dbKjTg23VLHtj3t+7ySj16BUdaohsiAimUV4qr70GrugD7OKCJI+xdcEtEoQWoNtwLAqInJoo4SAog8B3QNsM0EuzogtVRjZHyvfvs7DF4o+8Pl1ZN3bdUlNnuluiuXS5nixCLghHxkhNkPr/90Fhg2ONUMboLgOCXwtKpPXU6rOT2+fCS5ZElYBVTJIcmJofCNDRPfVegzXTTB2HQvxCqpQj13fXKMHkEJa,iv:zoXqfpDGyHgo3FoNzemVw1Z3EzRzXyYzbO3cm8Xw8dM=,tag:98fgA0Tg71SYuIWcyCuoAw==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN29VWk5MdWJzS0tzaXJ3
            OXVzUDA2amFaaWxjUGl6MXRpdlpYeUpVazNzCkJRN3JXV0VrblNSSU1wQ2MzZkhO
            VmoydG9MTWZmWWY1RTZpUnA3dTB5clEKLS0tIDdDOXVUK2JkOGkwODQvTTNPbVNM
            MWVVaXBXZ2lPSS9jeDh1amUzaU5ZM0kKHHtbC6EqmbwcCzUTha08n5Rtzh8S5sfy
            sKUtc8dh5AqlOpTPbCShhimz+Av/eWwNYW7Ya77ZfER0wx+niu6aeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:12Z"
    mac: ENC[AES256_GCM,data:n+yCqH1CxCV26vwx75VNuQQJYHyXwzaTopKDoNSlY7RbY2dHc8V5qeRKim+cpTbOuV7yvZ01dsmuO7Iwh8bF6v6RzpQWZgoD8YFtNnCYtqFOcm7ZWGCcAnZQEeayZ/fJ6A58iC/YDvkf061Jn8I24Ug2U5PN2dNwLS8oSRByo7w=,iv:AWfPR5B/9yQbuakPFX0AqRckxAR8mouMpKfg8c5KVRM=,tag:X/t1BDEbxhCV3GXvIrw1Qg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
