kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    client_id: ENC[AES256_GCM,data:jvbivZLLHnUWqdrQDZxqdNc=,iv:PLmgUx4N9jD0GeaEwdHXvuYjh/Ly0RDdsS3Tp40swVU=,tag:tgEEeRdxd++tAhwxIBZJRA==,type:str]
    client_secret: ENC[AES256_GCM,data:Jd/ia1Enbf6pecxmRRordknsa5U6G5rzMizkVkPy8U23DrpvZg0A5GRxU9BMcy6pz1Z2UjNR3L+vgwGnb3rX,iv:m1BLMM05LhZxhSd+80orIO++Z5MfpyqX2mhAxXveRng=,tag:3vJwjq3hmjRcyqEx1LBbrQ==,type:str]
sops:
    age:
        - recipient: age1v6dnmkex8qstz8wrp3as58ap8yecvp5gttt67hktepc7s9kluvvsz94664
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUTJhalJpN1pmalpFandQ
            bkN6RG5Hajd6UWMwOHc3OWNKYjV5by9HSlRvCmxsUVV4emYxNVNFRUd4N241SlA0
            ejREK2JqclRFRXVCTjZ5VUU5a2V2bk0KLS0tICs2bjBmNWRsMWxMWWFsTVhHSlBI
            ZzA2Q1hSTTBJQmhFSDdtMjFqVmVZb3cKFlaTbokCT1FdNA+mFn4VixlmIDoRQNZ9
            OmfcAWx6yAb9Lc+8BH0E0tebWJwpm3UCcxlkz95lI+zp50P6taZbOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T13:34:37Z"
    mac: ENC[AES256_GCM,data:WEoOs2WFeJzGmr6NPAtZ/0XPgC0bTsta29mDzUDJ4g5143FW5Q1jVHswz3+/GoSGJyy0hg/aDGRgwLRjMoZ2Y0rUWCSPHJurb2kseLH0VOCtYZZDVj3J+fSRR/P6Rwj/w8xm1/pRgXjDAtOjRW9+tzDSnjcn2enG1k2nrTYl2V4=,iv:4ITD3by01RUl9VsYBru2qxaCLwLyi7RxP7ai8JkQ1pA=,tag:tGtdgwoAbiUy1Bx8EQtvAw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|project|destination|syncPolicy|repoURL|chart|targetRevision|registry|tag|repository)$
    version: 3.12.2
